spinnaker/halyard

halyard-web/config/halyard.yaml
halyard-web/src/main/java/com/netflix/spinnaker/halyard/Main.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/config/v1/HalyardConfig.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/UnknownPropertyException.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/Halconfig.java

Notice that it validates your halconfig & reports failures with line & column numbers pointing to the incorrect fields.
@duftler @jtk54 @ttomsu PTAL

Report halconfig contents

---

halyard-web/halyard-web.gradle
halyard-web/src/main/java/com/netflix/spinnaker/halyard/config/v1/HalconfigParser.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/config/v1/ResourceConfig.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/DeploymentConfiguration.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Account.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Provider.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Providers.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/kubernetes/DockerRegistryReference.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/kubernetes/KubernetesProvider.java
halyard-web/src/test/groovy/com/netflix/spinnaker/halyard/config/v1/HalconfigParserSpec.groovy
lombok.config

@duftler @jtk54 @ttomsu @danielpeach  PTAL
Also added a pair of unit tests.
#2

Provide fields used to configure Kubernetes

---

halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Providers.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/dockerRegistry/DockerRegistryProvider.java

Closes #2 
Next we start to validate configuration.

Provide docker registry configuration

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/ValidateNotNull.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/providers/ValidateFileExists.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/UpdateableSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/providers/AccountSpec.groovy

I also changed the validator error message to omit the field name explicitly, and rather format the error message to contain the field name when applying all validators.
@duftler or @ttomsu or @jtk54 PTAL

Added file & null value validation

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/UpdateableSpec.groovy

@duftler or @ttomsu or @jtk54 PTAL

Allow user to validate field w/o update

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java

Last doxygen comment change wasn't picked up

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/ValidateAccount.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/UpdateableSpec.groovy

@duftler or @ttomsu or @jtk54 PTAL

Add class-wide validation for accounts

---

build.gradle
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/v1/RetrofitConfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/providers/kubernetes/ValidateKubernetesAccount.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/v1/HalconfigParserSpec.groovy

@duftler or @ttomsu or @jtk54 PTAL
I had to add the retrofit config to get the k8s client to start.

(kubernetes) validate k8s account

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

Adds endpoints for showing configured spinnaker deployments

---

CONTRIBUTING.md
docs/project-structure.md

First pass at the contributing doc.
@duftler @ttomsu @jtk54 @ewiseblatt @skim1420 PTAL (this is not high-priority until I get closer to completing kubernetes & gce validators).

Contributing doc defined

---

halyard-cli/halyard-cli.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ShowCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/Color.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/Ui.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/Halconfig.java

@ewiseblatt @ttomsu @jtk54 PTAL
I haven't refactored the UI class yet, but that's incoming. 
Also I tried to record a gif of what the flow look like, but the pacing is strange since it seems to allot 1 frame per character drawn or so:

(cli) show command

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/config/ConfigNotFoundException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeIteratorFactory.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/LookupService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java

Lookup provider for more generic node retrieval

---

README.md
halyard-cli/halyard-cli.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/GetKubernetesAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiMessageList.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiParagraphBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiPrinter.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiSnippet.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiStoryBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiUi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeReference.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java

See the updated readme for how the new command structure looks.
@duftler @ewiseblatt PTAL

(cli) Flush out show command & description

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractProviderEnableDisableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/DisableKubernetesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/EnableKubernetesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiUi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Halconfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Webhooks.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/LookupService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/UpdateService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java

This paves the way for having halyard write field updates.
@ewiseblatt @duftler PTAL

Set enable/disable of provider

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Halconfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/BillOfMaterials.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/ComponentName.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/ComponentProfile.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/profileRegistry/ComponentProfileRegistry.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/profileRegistry/ComponentProfileRegistryService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/profileRegistry/StoredObjectMetadata.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java

@jtk54 @duftler @ewiseblatt PTAL

Parse BOM from GCS to get service config

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

@duftler @jtk54 PTAL
Nothing fancy, just a few simple validations

Docker registry validator

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesAddAccountCommand.java

Add docker account CLI command

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/GoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/GoogleAccountValidator.java

Google account validator

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleCommand.java

Google add account command

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesAddAccountCommand.java

Waiting on https://github.com/spinnaker/halyard/pull/50
See https://github.com/spinnaker/halyard/issues/49

Correct help-text behavior

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractDeleteAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/DeleteAccountCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java

@duftler Should be a quicky
Adds an endpoint accepting a DELETE verb by account & provider name, as well as the corresponding CLI command.

Delete account command

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractNamedProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiFormatUtils.java

Improve formatting for providers & accounts

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java

Separate display of global & local parameters in help text

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiUi.java

Edit kubernetes account command

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryEditAccountCommand.java

@duftler PTAL - I'll be making the changes we talked about for `updateStringList` readability in the next PR.

Edit docker account

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesEditAccountCommand.java

Cleanup edit kubernetes account command

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleEditAccountCommand.java

Edit google account

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractProviderEnableDisableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/GetAccountCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ProviderEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiMessageList.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiParagraphBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiStoryBuilder.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/BillOfMaterials.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/profileRegistry/ComponentProfileRegistry.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/profileRegistry/ComponentProfileRegistryService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/profileRegistry/StoredObjectMetadata.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/ProvidersValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/Main.java

Also cleaned up license headers
@duftler or @jtk54 PTAL

Smooth out some rough edges for beta testers

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/DaemonResponse.java

1. In the CLI, handle the (expected) `IllegalArgumentException`.
2. In the Daemon, differentiate between `HalconfigExceptions` and everything else.
@jtk54 or @duftler PTAL

Strengthen exception handling

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiUi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Halconfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/GoogleAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

Add more k8s option, punctuate properly, fix location formatting

---

build.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractListAccountsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractNamedProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ListAccountsCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ProviderCommand.java

Closes https://github.com/spinnaker/halyard/issues/69

List accounts command

---

README.md
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/GenerateService.java

This is a migration path to halyard, as well as a tool for specifying more complicated config.
@duftler or @jtk54 PTAL

Allow user to specify per-deployment services

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ConfigService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/LookupService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/SpinnakerComponent.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/DeploymentConfigurationSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/NodeSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/LookupServiceSpec.groovy

Lookup service testing

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/HalconfigParserMocker.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/LookupServiceSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/ValidateServiceSpec.groovy

@duftler or @danielpeach or @jtk54 PTAL

Test validation service's config traversal

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/AbstractConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/FeaturesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractNamedProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/FeaturesService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java

Right now these correspond to what's configurable in deck outside of netflix-only features.

Set feature flags in your halconfig

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/ClouddriverComponent.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/ComponentConfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/SpinnakerComponent.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/SpinnakerComponentSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java

Track required files during config generation

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/appengine/AppengineCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/appengine/AppengineEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/CommonGoogleCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/CommonGoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/appengine/AppengineAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/CommonGoogleAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/GoogleAccountValidator.java

https://github.com/spinnaker/halyard/issues/71
@danielpeach @duftler PTAL
This doesn't support all flags for the CLI (although the backing model has them), and doesn't do validation yet.

Stub out appengine support

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/problem/Problem.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/CommonGoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/LookupService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java

Fix javadocs breaking build

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/ClusteredSimpleDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/kubernetes/KubernetesClusteredSimpleDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerArtifact.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerEndpoints.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java

Bootstrap spinnaker & clouddriver

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractGetAccountCommand.java

Closes https://github.com/spinnaker/halyard/issues/86

Don't validate account loading during update

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/AtomicFileWriter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/AccountDeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/ClusteredSimpleDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/kubernetes/KubernetesClusteredSimpleDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java

After talking to @ewiseblatt & @jtk54 I'm tabling using `apt` to pull from the repos, since pulling from a bucket will probably be easier. But I'll keep the pin-file in place since it could still be useful.
@duftler or @danielpeach or @jtk54 PTAL

Generate pin file for debians

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonEvent.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/TaskController.java

Allow halyard to stream task results

---

build.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/appengine/AppengineCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/appengine/AppengineEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/google/GoogleEditAccountCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/appengine/AppengineAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java

(appengine) add + edit + validate

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/problem/ProblemBuilder.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/kubernetes/KubernetesFlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerArtifact.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerEndpoints.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/endpoint/EndpointType.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

This deploys the remaining microservices. Since front50 isn't configurable yet this won't work using pure-halyard deployment configuration.

Deploy remaining kubernetes services for a full clustered deployment

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/AbstractConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/PersistentStorageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/PersistentStorage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/LookupService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PersistentStorageService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java

Configure (without validating) front50

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/config/ParseConfigException.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50Profile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileConfig.java

Generate contents of front50 config

---

Dockerfile
Dockerfile.slim
cloudbuild.yaml

@ttomsu PTAL (pretty much copied from fiat)

Adds dockerfile for build triggers & GCR

---

build.gradle

Bumps spinnaker gradle plugin version

---

Dockerfile.slim
cloudbuild.yaml

Use installDist instead of distZip

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/EndpointFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/kubernetes/KubernetesFlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50Profile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java

This will be needed by deck's config

Pass spinnaker endpoints to profile configuration

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ConfigService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/FeaturesService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PersistentStorageService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/AccountServiceSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/ConfigServiceSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/FeaturesServiceSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/PersistentStorageServiceSpec.groovy

Create more service unit tests

---

docs/adding-a-provider.md

Guide for adding a provider

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiErase.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiSnippet.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonStage.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/EndpointFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java

Improve hal's presentation of event messages

---

build.gradle
halyard-cli/Makefile
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditPersistentStorageCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/PersistentStorage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PersistentStorageService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/PersistentStorageValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/ValidatorCollection.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java

Closes https://github.com/spinnaker/halyard/issues/106

Validate front50

---

halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy

Reeenable provider test

---

AUTHORS
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureEditAccountCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/azure/AzureAccountValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/LookupServiceSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/ValidateServiceSpec.groovy

This validates that the service principal credentials work and that the KeyVault exists. More work could be done to validate the permissions and secrets for the vault. Azure storage config will also need to be added separately.
#119

Add basic Azure support

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/resource/v1/StringResource.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/resource/v1/TemplatedResource.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/EndpointFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java

@danielpeach or @duftler or @jtk54 PTAL

Generate settings.js

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/DeploymentEnvironmentCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditDeploymentEnvironmentCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditPersistentStorageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/FeaturesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/PersistentStorageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/DeploymentTypeConverter.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/RunDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentEnvironmentService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentEnvironmentController.java

I also did a little restructure of the storage & features commands - check out the updated README for details.

Allow user to specify deployment options

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50Profile.java

With these changes (and the halconfig changes I made in other repos) Spinnaker is fully functional after being configured and deployed with Halyard alone. @duftler @jtk54 @danielpeach PTAL

Front50 configuration fixups

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractDeleteAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractListAccountsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/GetAccountCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommand.java

@duftler @jtk54 @danielpeach PTAL (mainly just renaming)

Rename account commands for consistency

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/aws/AwsAccountValidator.java

https://github.com/spinnaker/halyard/issues/116
@duftler PTAL
@gardleopard PTAL

AWS config

---

InstallHalyard.sh

Install script for Halyard (simplifies debian install path)

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

	Provide help-text for trailing newlines

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/SecurityCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/OAuth2Command.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authn.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/OAuth2.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Security.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/SecurityService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/OAuth2Validator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/SecurityValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SecurityController.java

This is setting up the boilerplate for a more meaty validation + edit PR coming tomorrow.

Oauth (for google) support

---

CONTRIBUTING.md

@lwander updating to describe xcrun error and workaround

updating contributing doc with mac xcode requirement

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/EchoProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/FiatProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50Profile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/IgorProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/registry/ProfileRegistry.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/registry/WriteableProfileRegistry.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/registry/WriteableProfileRegistryConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/registry/WriteableProfileRegistryProperties.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfileSpec.groovy

https://github.com/spinnaker/halyard/issues/114

Stubout support for updating the halconfig bucket

---

README.md

Fix readme typos.

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/AbstractConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/AbstractAddBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/AbstractBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/AbstractEditBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/AbstractGetBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/AbstractListBaseImagesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/BakeryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleAddBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleBakeryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleEditBakeryDefaultsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleEditBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/BaseImage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/HasImageProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeIteratorFactory.java

Google-specific rosco commands added

---

cloudbuild.yaml

Adds 'latest' tag and rm unshallow step to cloudbuild.yaml

---

cloudbuild.yaml

Fix typo in cloudbuild.yaml

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java

The preferences need to be separated, and the file writer needs to commit the result.

Fix debian install pinning. 

---

build.gradle

Needed for consuming newer version of clouddriver. @lwander PTAL

bumping version of dependencies

---

InstallHalyard.sh
README.md

* Command needs to be run as root.
* Config dir is created.
* tmp dir is deleted.

Improved install flow

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishBomCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishProfileCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/PathExpandingConverter.java

Closes https://github.com/spinnaker/halyard/issues/186

Expand relative paths passed to CLI

---

build.gradle
docs/adding-a-provider.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackEditAccountCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackAcountValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java

- Updating dependency version of halyard
- Adding cli support of openstack config
- Adding validation support of openstack config
TODO (in a future PR):
- use credentials to connect to openstack instance to verify configuration
- add optional rosco configuration options
@lwander PTAL

Openstack support in halyard

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java

@lwander PTAL - missed this check.
@EricJizbaMSFT this should fix your problem, but if it doesn't ping me!

bugfix (openstack) only grabbing region when openstack account is enabled

---

InstallHalyard.sh
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java

Update installer to place halconfig in right path

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerArtifact.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50Profile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java
halyard-deploy/src/main/resources/apache2/ports.conf
halyard-deploy/src/main/resources/apache2/spinnaker.conf
halyard-deploy/src/main/resources/debian/install.sh

https://github.com/spinnaker/halyard/issues/108

Configure apache2

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java

I also updated the spacing on the initial `hal` command, see here:

Print halyard CLI version

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfile.java
halyard-deploy/src/main/resources/debian/install.sh

Fixes: 
* Halyard & Spinnaker deb sources being intermingled
* Bug where config is written twice.

Fixup the debian install path

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/DeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/DiffDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiFormatUtils.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeDiff.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/NodeSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

feat(halyard) Diff configs between deploys

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/appengine/AppengineAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/GoogleAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackAcountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/util/ValidatingFileReader.java

This makes it clearer why Halyard (and subsequently Spinnaker) is unable to read a file.
Closes https://github.com/spinnaker/halyard/issues/174

feat(config) Show halyard user when permission denied to file

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

Also prevent users for adding same registry twice.

fix(config): Fix error help messages for bad key format

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/EndpointFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/EchoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/FiatService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/Front50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/IgorService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RoscoService.java

This way even local deployments can be made public.

fix(deploy): Make null the default host

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/OperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesOperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java

I made some small changes moving orca logic into the top-level provider interface, as well as sped up deployment time by only red-blacking during updates.

feat(deploy): Block ingress into Spinnaker namespace

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java

I realized I had omitted this from the CLI making config on a VM a little trickier.

feat(cli): Add --kubeconfig-file option to k8s

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/BillOfMaterials.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/monitor/v1/DashboardFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/OperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesOperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerArtifact.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerEndpoints.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerMonitoringDaemonProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerMonitoringDaemonService.java
halyard-deploy/src/main/resources/debian/install.sh
halyard-deploy/src/main/resources/monitor/dashboards/datadog.sh
halyard-deploy/src/main/resources/monitor/monitoring.sh

This was going to be part of a larger commit setting up the sidecars, but we need the BOM change to continue publishing releases to actually build the sidecars.

feat(deploy): Mount monitoring secrets for kubectl

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerArtifact.java

Note the k8s install path will still be broken until this is built: https://github.com/spinnaker/orca/pull/1231

fix(deploy): Assorted fixes

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineEditAccountCommand.java

fix(appengine) set default local repo directory

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/BillOfMaterials.java

feat(bom): Add fields for improved traceability

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/RunDeployCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/MetricStores.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/AccountDeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/OperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/SizingTranslation.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesOperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesSizingTranslation.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/RunningServiceDetails.java

I also wound up adding rudimentary instance sizing support.

feat(deploy) auto-connect to k8s

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AccountCommandProperties.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Account.java

Please check my wording for the help text.

feat(config): Configure required group memberships

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/AccountDeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesOperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java

jtk: Here's what you'll need to run (more or less) to deploy to k8s
```
gcloud container clusters get-credentials tri-radial-eu --zone europe-west1-d
hal config version edit --version nightly
hal config provider docker-registry enable
hal config provider docker-registry account add my-gcr-account --password-file ~/.gcp/vault-nits.json --username _json_key --address gcr.io
hal config provider kubernetes enable
hal config provider kubernetes account add my-k8s-account --docker-registries my-gcr-account
hal config provider google enable
hal config provider google account add my-gce-account --json-path ~/.gcp/vault-nits.json --project nits-1132
hal config storage edit --account-name my-gce-account
hal config deploy edit --type flotilla --account-name my-k8s-account
hal deploy run
```

fix(deploy): Fixups needed for deploy validation

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditDeploymentEnvironmentCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditSecurityCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/SecurityCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java

Also change format of consul & vault flags

feat(cli): Add flags for configuring external IPs

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Security.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesOperationFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerEndpoints.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerPublicService.java

If you provide a correct ui & api + domain & address alongside configured authn methods this'll deploy spinnaker on k8s as a protected, publicly facing service.

feat(deploy): Deploy Kubernetes services w/ public IPs

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/OrcaRunner.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java

Now it shows why the pipeline failed, and what stages it's running.

feat(deploy): Improve logging granularity from Orca

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/appengine/AppengineAccountValidator.java

@lwander please review.
Closes https://github.com/spinnaker/halyard/issues/288
Another related piece that I verified:
If you a). don't have valid credentials or b). haven't enabled the App Engine Admin API, you'll get a 403 error - but the API's error messages are different in those two cases, are surfaced to a Halyard user, and are quite clear.

fix(appengine) validate if appengine app exists

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfileFactory.java

This write the provider's account config into rosco.yml

feat(config): Generate rosco account config

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfileFactory.java

feat(version): Write BOM version for Deck

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java

feat(cli): Failure messages

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/appengine/AppengineAccountValidator.java

@lwander please review.
@idoshamun FYI.

feat(appengine): adds known host configuration options

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineCommand.java

fix(appengine): add docs link

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiMove.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiParagraphBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiSnippet.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/OrcaRunner.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/DistributedService.java
halyard-web/config/halyard.yml
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AdminController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/BakeryController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentEnvironmentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MasterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MetricStoresController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SecurityController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/WebhookController.java

This lets us deploy all spinnaker components in parallel, and then surface it nicely in the UI:

feat(daemon & cli) support child tasks

---

InstallHalyard.sh
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalService.java
halyard-web/etc/init/halyard.conf
halyard-web/etc/init/halyard.conf.gen

https://github.com/spinnaker/halyard/issues/341

feat(daemon): Run as $USER

---

InstallHalyard.sh

fix(install): Install was broken from within docker container

---

halyard-deploy/src/main/resources/debian/pre-bake.sh

Each service was already stopped

fix(deploy): No need to stop spinnaker during bake

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

@lwander I created the corresponding commit in deck: https://github.com/spinnaker/deck/pull/3581, but do I need to do anything else in order for halyard to consume that after it's merged? Do I need to update spinnaker dependencies or something?
#119

feat(deploy): Add default Azure settings to deck

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/AbstractConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/EditOAuth2Command.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authz.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/GroupMembership.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/OAuth2.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/Main.java

Add preEstablishedRedirectUri

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishLatestCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishVersionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/WriteableProfileRegistry.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AdminController.java

`hal admin publish version --version 0.1.0 --alias "Optimist Pram" --changelog TBD`
`hal admin publish latest 0.1.0`

feat(admin): Publish versions

---

build.gradle
halyard-web/lib/systemd/system/halyard.service

chore(install): Systemd startupfile

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java

Note this only affects help-text, functionality should be unaffected. @ttomsu FYI

fix(cli): --version is not global

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/consul/ConsulClientProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConsulClientService.java
halyard-deploy/src/main/resources/services/consul/client/install.sh
halyard-deploy/src/main/resources/services/consul/client/startup/startup-consul.sh

Seems any edits to /etc/resolveconf/resolv.conf.d/* are overwritten
@jtk54 FYI

fix(deploy): Edit resolveconf on startup, not bake

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/AbstractRemoteActionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/TaskCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/LogLevelConverter.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/task/InterruptTaskCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/task/ListTaskCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/error/v1/HalException.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/job/v1/JobExecutor.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/job/v1/JobExecutorLocal.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/problem/v1/Problem.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/problem/v1/ProblemSet.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskInterrupted.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/OrcaRunner.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/VaultService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesRedisService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/TaskController.java

There seems to be some resource leakage going on in Halyard. This allows us to troubleshoot.

feat(core): task commands for interruption

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java

https://github.com/spinnaker/halyard/issues/397

feat(deploy): Use clone, rather than deploy in RB pipelines

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/AbstractRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/github/EditGithubRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/github/GithubRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/google/EditGoogleRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/google/GoogleRoleProviderCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/GithubRoleProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/GroupMembership.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/RoleProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/SecurityService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/GithubRoleProviderValidator.java

This gets the feature 95% of the way there, but as discussed yesterday, I am going to remove the extra `roles` layer to match the authn command

feat(authz): Adds GitHub Teams as authz provider

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/CustomProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConsulClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConsulServerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerMonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpringService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultServerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianGateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianRedisService.java

The goal of this is to enable supplying custom rosco packer templates & scripts more easily.

feat(deploy): Copy any custom user profiles

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java

That first command's help text is primarily noise

fix(cli): Shorten main command help text

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RedisConfProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleRedisBootstrapService.java
halyard-deploy/src/main/resources/services/redis/redis.conf

Clouddriver discovers & enters cache keys remotely now

feat(deploy): Deploy redis

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleVaultServerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesRedisService.java

This will be useful for reading health status from the consul API.

feat(deploy): Connect to sidecar services

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianDeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedServiceDelegate.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleEchoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleFiatService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleFront50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleGateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleIgorService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleOrcaBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleOrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleRedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleRoscoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesGateService.java

This deploys (but doesn't support updating yet) a full, clustered spinnaker on GCE. It also includes some startup tweaks that need to be baked into our images.

feat(deploy): full deployment of spinnaker on GCE

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/provider/v1/google/GoogleCredentials.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/ProfileRegistry.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/WriteableProfileRegistry.java

Our nightly builds have run into this a few times now.

fix(bom): Extend GCS request timouts

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth2/EditOAuth2Command.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth2/OAuth2Command.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/OAuth2ProviderTypeConverter.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authn.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/AuthnMethod.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/OAuth2.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/SecurityService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/OAuth2Validator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringConfig.java

This reverts commit a7d051b452dfaa680f099b7ed34d26da309afc7c.
Oops.

chore(oauth): Revert change from oauth2 to oauth

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/GoogleAccount.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverBootstrapProfileFactory.java

This change only manifests itself on the bootstrapping clouddriver.

fix(deploy): Remove groupmembership from bootstrapping account

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

closes: https://github.com/spinnaker/halyard/issues/442

fix(deploy): Display gcloud specific kubectl remediation

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ConfigService.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/StringBodyRequest.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java

This was previously only possible via a direct edit to your halconfig.

feat(cli): --set-current-deployment

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/AbstractRemoteActionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/DeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ApplyDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ConnectDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/BakeDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/MetricRegistryProfileFactoryBuilder.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/BakeServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianServiceProvider.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

feat(cli): hal deploy connect

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverBootstrapProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/FiatProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/IgorProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/ApacheSpinnakerProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalService.java

Looks like I was omitting group before, perhaps this is why some services didn't have trouble, but Rosco did.

fix(deploy): spinnaker user & group must own all files

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java

Running `hal XYZ -q --log all` is much more automation friendly

feat(cli): Better log output

---

halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/kms/v1/SecureStorage.java
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/kms/v1/google/GoogleKms.java
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/kms/v1/google/GoogleSecureStorage.java
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/kms/v1/google/GoogleSecureStorageConfig.java
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/kms/v1/google/GoogleSecureStorageProperties.java
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/kms/v1/google/GoogleStorage.java
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/services/v1/BackupService.java
halyard-web/config/halyard.yml

This only encrypts & stores a single file - it doesn't address versioning & restoring backups yet.

feat(backup): Add ability to securely backup halconfig

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/RelaxedObjectMapper.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java

This makes it impossible to add new features to bom.yml or versions.yml w/o breaking all old clients.

fix(core): Don't fail on unknown properties for shared files

---

docs/commands.md
docs/deprecating-commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/DeprecatedCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishLatestHalyardCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishLatestSpinnakerCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AdminController.java

In the process I documented how to deprecate commands (had to happen here).

feat(version): Publish a latest stable halyard version

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditVersionCommand.java

@ewiseblatt What do you think about this wording?

fix(cli): version edit wording to match aliases

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedLogCollectorFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesProviderUtils.java

@skim1420 thanks for catching this

fix(logs): Collect logs should be scoped to namespace

---

cloudbuild.yaml

chore(cloudbuild): Extend halyard timeout to 25 min

---

README.md

chore(readme): Updated stable warning to beta notice

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java

Without this, the rollback fails with an `asg_dynamic_ancestor` error, which is cryptic unless you're familiar with Spinnaker's internals.

fix(rollback): Fail early when rollback impossible

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java

fix(deploy): Set default bake account in orca

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesProviderUtils.java

Ingress isolation was not behaving as I expected. Will need to find another solution for this.

fix(provider/kubernetes): Disable ingress isolation

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ApplyDeployCommand.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/BakeDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeployOption.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RedisService.java

feat(deploy): Only flush infra cache when specified

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/AccountValidator.java

Hi,
Just made a couple of grammar changes that I came across when doing the setup.

Some minor grammar changes in the account validator

---

halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/services/v1/BackupService.java

Attempts to close https://github.com/spinnaker/halyard/issues/590

fix(backup): Close all opened entries

---

docs/commands.md

Sorry @johnrengelman - forgot to remind you to generate these docs
https://github.com/spinnaker/halyard/pull/623

chore(docs): Adds daemon parameter to docs

---

release/publish.sh

fix(release): Fix typo in docker tag command

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditDeploymentEnvironmentCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/SharedDistributedServiceSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesEchoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesFiatService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesFront50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesGateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesIgorService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesMonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesOrcaBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesOrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesRedisBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesRedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesRoscoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesSharedServiceSettings.java

Same changes as https://github.com/spinnaker/halyard/pull/652
Travis was failing due to some weird git history issue.

feat(halyard): Adding deploy location with provider specific defaults

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDeckService.java

fix(deploy): Correctly mount custom settings.js in k8s

---

halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy

We missed this when we did some re-branching last week.
This PR had it: #652 It was approved but not merged.
This PR didn't: #654 It was merged.

Add spec example for the location property on deployment configuration.

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/ldap/EditLdapCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/ldap/LdapCommand.java
halyard-cli/src/test/groovy/com/netflix/spinnaker/halyard/cli/command/v1/CommandTreeSpec.groovy
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authn.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/AuthnMethod.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Ldap.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/SecurityService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/LdapValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/validate/v1/security/LdapValidatorSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/LdapConfig.java

I've added settings and corresponding tests to enable ldap authentication.

Add authn Ldap settings to halyard

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java

This fix should address the problem, but my hunch is that something
deeper is still going on in orca as it's unable to see the prior
deployed server group's account.

fix(deploy): No account field

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/CiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisEditMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisMasterCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisMaster.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java

* hal config ci travis master add opensource --address "https://api.travis-ci.org" --base-url "https://travis-ci.org" --github-token
* hal config ci travis enable

feat(ci/travis) Add support for travis

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedServiceSpec.groovy

See issue #670 
Example Usage:
```
kubernetes:
imagePullSecrets:
- desired-image-pull-secret
```

Feat(Deployment) Add imagePullSecret Kubernetes Service Setting

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedServiceSpec.groovy

Implementation of feature proposed in [issue 736](https://github.com/spinnaker/halyard/issues/736)

Feat(deployment) adds replicas setting to custom sizing

---

halyard-deploy/src/main/resources/debian/install.sh
halyard-deploy/src/main/resources/debian/pre-bake.sh

fix(docs): Error messages imply >=14.04 works, other LTS do not work

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfileFactory.java

fix(bootstrap): NPE in checking bootstrap profiles

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

feat(provider/kubernetes): allow users to set ips behavior

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/AbstractRemoteActionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ApplyDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalGitDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/git/LocalGitService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/git/LocalGitServiceProvider.java
halyard-deploy/src/main/resources/git/prep.sh
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

We need to get all git repos locally before we can generate config for them

feat(deploy): Add hooks to 'prep' a deployment

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

Add missing docker registry parameters:
* clientTimeoutMillis
* cacheThreads
* paginateSize
* sortTagsByDate
* trackDigests

feat(docker): Add missing parameters

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalGitDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConsulClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConsulServerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/EchoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/FiatService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/Front50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/IgorService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RoscoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerMonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultServerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/git/LocalGitRedisService.java

chore(local_git): Spelling error.

---

halyard-web/pkg_scripts/postInstall.sh

fix(install): Add shebang to /usr/local/bin/hal

---

install/Installer.sh

feat(install): Allow bucket override

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ApplyDeployCommand.java

Please close if you think it's unnecessary. I noticed it and thought I'd fix it.

Fixed spelling mistake

---

halyard-deploy/src/main/resources/git/prep.sh

@lwander the `echo_err` function is missing in this script

add missing echo_err function to prep.sh

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/provider/v1/google/GoogleCredentials.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GoogleProfileReader.java

Cherry pick of https://github.com/spinnaker/halyard/pull/794

feat(bom): read application default creds if available

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/pubsubs/google/GoogleAddSubscriptionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/pubsubs/google/GoogleEditSubscriptionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/pubsubs/google/GooglePubsubCommandProperties.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/pubsub/google/GoogleSubscription.java

https://github.com/spinnaker/echo/pull/220

feat(pubsub): message format parameter

---

release/all.sh

Add release.useLastTag=True to release script.

---

halyard-cli/Makefile
install/Installer.sh
release/all.sh

@lwander 
These are the additional cherry picks.

Release 0.40.x

---

Dockerfile
Dockerfile.local
Dockerfile.slim

chore(docker): Upgrade base image (#2298)

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java

closes: https://github.com/spinnaker/spinnaker/issues/2324

fix(deploy/kubernetes): v1 deploys broken by orca refactor

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/jenkins/JenkinsAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/jenkins/JenkinsCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/jenkins/JenkinsEditMasterCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/jenkins/JenkinsMaster.java

Relies on https://github.com/spinnaker/igor/pull/222.

feat(jenkins_master): Add CSRF config for Jenkins Masters.

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/HalconfigValidator.java

https://github.com/spinnaker/halyard/issues/843

fix(update): provide correct update message

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/HalconfigValidator.java

Don't upgrade everything, just spinnaker-halyard

fix(updates): correct update instructions

---

halyard-web/config/halyard.yml

Disable the grpc server, since its not used by default.

feat(grpc): Disable grpc server by default.

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/http/HttpAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/http/HttpArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/http/HttpArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/http/HttpEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/http/HttpArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/http/HttpArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ArtifactProviderService.java

Depends on https://github.com/spinnaker/clouddriver/pull/2395

feat(artifacts): Add support for HTTP artifact accounts

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

I didn't add --custom-resources support to the CLI since it felt clunky - it's easy enough to edit in the halconfig for now.
@wjoel FYI

feat(kubernetes/config): Support kind, omitKind & customResources

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/execReadinessProbe.yml

It's not totally clear why this is required only for some istio
clusters... but [this provides a
clue](https://github.com/istio/istio/issues/2628#issuecomment-358111686).

fix(kubernetes/health): istio-friendly health checks

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java

Previously (and unlike how we handled it for the v1 deploys) we were mounting files by their name on local-disk, which isn't always correct (most notably when mounting ~/.aws/credentials, which was being staged by halyard as ~/.aws/[front50/clouddriver]-credentials).

fix(deploy/kubernetes): v2 file mounts by name

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ApplyDeployCommand.java

Didn't bother to add the `--stage-only` flag to `ApplyDeployCommand` yet.
WDYT of the approach? Options include:
1) Go with what's here.
2) Contain the `stageOnly` checks to just `ApplyDeployCommand`. This will result in the repo's still being cloned, but no files will be generated in `~/.hal/default/staging`.
3) Decide it's too messy and not worth it and abandon it.

feat(localgit): Add --prep-only flag to just clone repos.

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java

(fixes spinnaker/spinnaker#2579)

Add the ability to enable infrastructureStages

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/s3/S3ArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/s3/S3ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java

Implement S3 artifacts in halyard to support https://github.com/spinnaker/spinnaker/issues/2595
Looking for feedback.

feat(artifacts) Implement S3 Artifacts

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleOrcaBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1OrcaBootstrapService.java

Fixes https://github.com/spinnaker/spinnaker/issues/2635

fix: Make clouddriver-bootstrap-local.yml and orca-bootstrap-local.yml usable by default

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/container.yml
halyard-deploy/src/main/resources/kubernetes/manifests/resources.yml

https://github.com/spinnaker/spinnaker/issues/2288

feat(deploy/kubernetes): v2 custom sizing

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2RoscoService.java

https://github.com/spinnaker/rosco/pull/245

feat(deploy/kubernetes): deploy rosco using v2

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubectlServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java
halyard-deploy/src/main/resources/kubernetes/manifests/secret.yml

https://github.com/spinnaker/spinnaker/issues/2288

feat(deploy/kubernetes): v2 clean

---

Dockerfile
Dockerfile.local

This patch fixes issue spinnaker/spinnaker#2703

fix(Dockerfile): Create home dir for spinnaker user in Dockerfile

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2IgorService.java

Fixes https://github.com/spinnaker/spinnaker/issues/2688

fix(deploy/kubernetes): v2 disable igor when needed

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/KubectlDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubectlServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2MonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceDelegate.java

https://github.com/spinnaker/spinnaker/issues/2288

feat(deploy/kubernetes): v2 monitoring enabled

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/jenkins/JenkinsAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/jenkins/JenkinsEditMasterCommand.java

fix(ci/jenkins): Adds argument to CSRF flag.

---

halyard-deploy/src/main/resources/debian/install.sh

closes https://github.com/spinnaker/halyard/pull/627

fix(install/debian): don't install java if not needed

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth2/EditOAuth2Command.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/OAuth2.java

Add Oracle oauth2 authn provider.

feat(authn/oauth2/provider/oracle): Added oracle oauth2 provider

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/bitbucket/BitbucketAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/bitbucket/BitbucketArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/bitbucket/BitbucketArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/bitbucket/BitbucketEditArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitlab/GitlabAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitlab/GitlabArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitlab/GitlabArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitlab/GitlabEditArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3AddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3ArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3EditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/bitbucket/BitbucketArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/bitbucket/BitbucketArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gitlab/GitlabArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gitlab/GitlabArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ArtifactProviderService.java

feat(artifacts): bitbucket, gitlab support; s3 cli support

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/FieldValidator.java

https://github.com/spinnaker/clouddriver/pull/2697

feat(provider/kubernetes): caching policy support

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java

issue: https://github.com/spinnaker/spinnaker/issues/3067

fix(halyard): Add merging default env with serviceSettings env.

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/CleanDeployCommand.java

fixes https://github.com/spinnaker/spinnaker/issues/3110 though doesn't mention anything kubernetes-specific since this command is for all providers

feat(docs): Clarify that clean doesnt delete hal config

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

https://github.com/spinnaker/clouddriver/pull/2869

feat(provider/kubernetes): support timeout seconds config

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

DNMY, still regenerating the docs.
https://github.com/spinnaker/deck/pull/5609

feat(wercker/travis): add stage feature flag support

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml

See https://kubernetes.io/docs/concepts/overview/working-with-objects/common-labels/

feat(deploy): set recommended app labels

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

https://github.com/spinnaker/spinnaker/issues/3297

fix(deploy): remove illegal version characters from label

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/iap/EditIAPCommand.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/IAPConfig.java

Fixes https://github.com/spinnaker/spinnaker/issues/3321.

fix(iap): set correct IAP fields.

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleAddBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleBakeryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleEditBakeryDefaultsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleEditBaseImageCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/oracle/OracleBakeryDefaults.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/oracle/OracleBaseImage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/oracle/OracleProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/oracle/OracleBakeryDefaultsValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/oracle/OracleBaseImageValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/oracle/OracleProviderValidator.java

Adding bakery capability to the oracle provider.
See also https://github.com/spinnaker/rosco/pull/273, https://github.com/spinnaker/orca/pull/2405, and https://github.com/spinnaker/deck/pull/5697.

feat(bake/oracle): Added oracle OCI bakery

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/oracle/OracleAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/oracle/OracleArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/oracle/OracleArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/oracle/OracleEditArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/oracle/OracleEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleCommandProperties.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/oracle/OracleArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/oracle/OracleArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ArtifactProviderService.java

Added oracle type artifact.  Related PR in clouddriver is https://github.com/spinnaker/clouddriver/pull/2990.

feat(artifact/oracle): Added oracle artifact.

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Pubsubs.java

fix(config/pubsub): Set pubsub global enabled based on child config.

---

build.gradle
gradle/buildViaTravis.sh
gradle/init-publish.gradle
gradle/installViaTravis.sh
halyard-web/halyard-web.gradle

Removes spring boot gradle plugin.
Ref: https://github.com/spinnaker/spinnaker/issues/2844

chore(builds): Introduces composite builds via gradle plugin.

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/SidecarConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/container.yml
halyard-deploy/src/main/resources/kubernetes/manifests/securityContext.yml

https://github.com/spinnaker/halyard/pull/1080

feat(deploy): support sidecar security context

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3AddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3ArtifactCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3EditArtifactAccountCommand.java

Fixes https://github.com/spinnaker/spinnaker/issues/3526

feat(artifact): document usage of s3 api endpoint and region

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java

Configuration for https://github.com/spinnaker/spinnaker/issues/3539
Clouddriver implementation: https://github.com/spinnaker/clouddriver/pull/3150

feat(appengine): add support for filtering appengine services and versions

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerMonitoringDaemonService.java

@lwander 
It isnt clear to me how the interfaces work so I'm just guessing here.

feat(deploy): Handle spinnaker-monitoring-local.yml

---

halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ArtifactAccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ArtifactProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/BakeryController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/CanaryController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/CiController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ClusterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentEnvironmentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/HaServiceController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MasterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MetricStoresController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/NotificationController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PubsubController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SecurityController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SubscriptionController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/WebhookController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/util/v1/GenericDeleteRequest.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/util/v1/GenericEnableDisableRequest.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/util/v1/GenericUpdateRequest.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/util/v1/RequestUtils.java

The follow-up to https://github.com/spinnaker/halyard/pull/1116 but for mutating requests.  This should make it a lot easier to write a controller, reducing the amount of work needed to add parameters to halyard.

 feat(controllers): Add new generic request handlers

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/NotificationCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/twilio/EditTwilioCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/twilio/TwilioCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notification.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notifications.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/notifications/TwilioNotification.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/NotificationService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Partially resolves https://github.com/spinnaker/spinnaker/issues/3757.
Corresponding PRs (should not be merged until next Halyard release):
- Deck: https://github.com/spinnaker/deck/pull/6279
- Docs: https://github.com/spinnaker/spinnaker.github.io/pull/1166

feat(notifications): Add Twilio SMS support

---

docs/commands.md

fix(docs): Autogenerate docs

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceTest.groovy

getSidecars should work even when there are no special settings applied.

fix(deploy): Make getSidecars work with default settings

---

halyard-config/halyard-config.gradle

Part of secrets management project. 
Depends on adding kork to spinnaker-dependencies here: https://github.com/spinnaker/spinnaker-dependencies/pull/279/files
[spinnaker/spinnaker#3649](https://github.com/spinnaker/spinnaker/issues/3649)

feat(config/secrets): add korkSecrets dependency to halyard-config

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/NotificationCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/AbstractAddPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/AbstractDeletePublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/AbstractEditPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/AbstractGetPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/AbstractHasPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/AbstractListPublishersCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/PubsubCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/google/GoogleAddPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/google/GoogleDeletePublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/google/GoogleEditPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/google/GoogleGetPublisherCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/google/GoogleListPublishersCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/pubsub/google/GooglePubsubCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/pubsubs/google/GooglePubsubCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Publisher.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Pubsub.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Pubsubs.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/pubsub/google/GooglePublisher.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PublisherService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PubsubService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/pubsub/google/GooglePublisherValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/pubsub/google/GooglePubsubValidator.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PublisherController.java

Sorry this PR is huge - there were a lot of points to hook into the infrastructure and I didn't realize how big it was getting.
tag: https://github.com/spinnaker/spinnaker/issues/2784

feat(notifications/pubsub): Adds support for Google Pubsub notifications

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfileFactory.java

This removes the unnecessary config from non-ImageProviders from the
config, also prevents unrelated config changes from bouncing rosco on hal deploy update.

feat(rosco/trim): Write only ImageProviders in rosco profile

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceTest.groovy

Allow adding nodeSelector to kubernetes service-settings
kubernetes:
nodeSelector:
kops.k8s.io/instancegroup: my-instance-group

feat(deploy/kubernetes): add nodeSelector to kubernetes service settings

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java

Fixes https://github.com/spinnaker/spinnaker/issues/3882

fix(spinnaker.yml): Add back host and port to SlimServiceSettings

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/KubectlDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubectlServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Executor.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceTest.groovy

This makes the intent of the methods as well as the used objects more
explicit and testable.

chore(deploy): Extract executor code to KubernetesV2Executor

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/secrets/SecretSession.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/secrets/SecretSessionManager.java

Part of secrets management project. 
Note: these classes will require the korkSecrets dependency in order to build.
[spinnaker/spinnaker#3649](https://github.com/spinnaker/spinnaker/issues/3649)

feat(config/secrets): add SecretSession and SecretSessionManager

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java

Part of secrets management project: https://github.com/spinnaker/spinnaker/issues/3649
Depends on halyard PR [#1157](https://github.com/spinnaker/halyard/pull/1157) and kork PR [#225](https://github.com/spinnaker/kork/pull/225)

feat(secrets): add decryption for kubernetes configs

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/maven/MavenAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/maven/MavenArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/maven/MavenArtifactCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/maven/MavenArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/maven/MavenEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/maven/MavenArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/maven/MavenArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java

feat(core): Add Halyard Maven Artifact account support

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryEditAccountCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryProviderValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

feat(cf): Add Halyard CF provider support

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

https://github.com/spinnaker/spinnaker/issues/3894
Adds feature flag "managed-pipeline-templates-v2" to show/hide the mptv2 UI.

feat(core): add feature flag for managed pipeline templates v2

---

docs/commands.md

https://github.com/spinnaker/spinnaker/issues/3632
https://github.com/spinnaker/spinnaker/issues/3942
Hi, @jmelchio , @jkschneider , I ran `make` for `/halyard-cli` post merge of https://github.com/spinnaker/halyard/commit/9906f59b3f684358234e31ead7c10367280fb16e and https://github.com/spinnaker/halyard/commit/74ff659184a694954957c2523aaf023e9b3ec3c5 and it picked up these documentation changes. Does this look good to merge? Thanks!

docs(halyard): document cloudfoundry and maven artifact cli support

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

Produces an error message like
and in the daemon logs

feat(docker): give a better error message during auth issues

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProviderSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy

modified:   halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
modified:   halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProviderSpec.groovy
modified:   halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy

feat(providers): getPrimaryAccount should respect bootstrap only.

---

install/macos/InstallHalyard.sh

osx intall script: remove -s option from call to su

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/GithubRoleProvider.java

Add missing annotation for secret field in `GithubRoleProvider`

feat(secrets): add secret annotation in GithubRoleProvider

---

halyard-config/halyard-config.gradle

Part of secrets management project: https://github.com/spinnaker/spinnaker/issues/3649

feat(secrets): add korkSecretsAws dependency

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java

This is to enable UDF files to be staged and deployed. Fixes https://github.com/spinnaker/spinnaker/issues/4058

fix(clouddriver/profile): Enable custom UDF files

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/IgorProfileFactory.java

We're moving parsing artifacts from Jenkins jobs to happen in igor, so Igor will need to know about any custom templates.

feat(artifacts): Include artifact template in igor config

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

fix(cf): Correct metricsUri and appsManagerUri configuration

---

install/macos/InstallHalyard.sh

fix https://github.com/spinnaker/spinnaker/issues/4352

fix(install): fix the problem with JDK 12.0

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml
halyard-deploy/src/main/resources/kubernetes/manifests/service.yml

Reverts spinnaker/halyard#1303

Revert "feat(kubernetes): Allow adding custom pod and service labels"

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml
halyard-deploy/src/main/resources/kubernetes/manifests/service.yml

A corrected version of #1303, sorry about that @ezimanyi.

feat(kubernetes): Allow adding custom pod and service labels

---

halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/services/v1/BackupService.java

* Generate name for backups that can be easily sorted

Change date format for backups

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

fix(cf): Strict validation of CF account appsManager and metrics URLs format
Value must be well formed `http` or `https` URL.

fix(cf): Strict validation of CF account appsManager and metrics URLs format

---

halyard-deploy/src/main/resources/kubernetes/manifests/httpReadinessProbe.yml

Fixes spinnaker/spinnaker#4568

fix(kubernetes): Fix readiness probe

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/NotificationCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/github/EditGithubStatusCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/notifications/github/GithubStatusCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notification.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notifications.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/notifications/GithubStatusNotification.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/NotificationService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Corresponding PR:
https://github.com/spinnaker/deck/pull/7239

feat(notifications): Add Github Status support

---

gradle.properties
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Toleration.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceTest.groovy

This is required if we want to deploy some spinnaker components on a specific node.
resolves https://github.com/spinnaker/spinnaker/issues/3541

feat(kubernetes): Support for tolerations

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditDeploymentEnvironmentCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/ImageVariantConverter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1EchoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1FiatService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1Front50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1IgorService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1KayentaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1MonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1OrcaBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1OrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1RedisBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1RedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1RoscoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2RedisService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

Supports `slim` and `ubuntu`, the former being the default.
Ubuntu image supported starting with v1.16.0.

feat(deploy/kubernetes): Option to select the image variant to deploy

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java

depends on https://github.com/spinnaker/kork/pull/370

refactor(deploy): Adapt to changes in kork-config

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notification.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notifications.java

Broken in #1374
Closes spinnaker/spinnaker#4834
cc @loispostula

fix(notifications): fix editing notifications in halyard

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Telemetry.java

Fixes https://github.com/spinnaker/spinnaker/issues/4872

fix(stats): Replace UUID with ULID as spinnaker instance idententifier

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitrepo/GitRepoAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitrepo/GitRepoArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitrepo/GitRepoArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitrepo/GitRepoEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gitrepo/GitRepoArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gitrepo/GitRepoArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ArtifactProviderService.java

Enables configuration through Halyard for the git repo artifact type added here: https://github.com/spinnaker/clouddriver/pull/4049
@ethanfrogers

feat(artifacts): add git repo artifact support

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsLifecycleHookUtil.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/aws/AwsAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/aws/AwsLifecycleHookValidation.java

Fixes https://github.com/spinnaker/spinnaker/issues/4851

fix(provider/aws): Support for specifying lifecycle hooks for AWS accounts

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GoogleProfileReader.java

This should fix https://github.com/spinnaker/spinnaker/issues/5089.
The anonymous Google storage credentials using `com.google.auth.oauth2.GoogleCredentials.newBuilder().build()` are breaking on `refreshAccessToken` - probably after the bump to version `v1-rev267-1.25.0`.
I'm not a GCS specialist so I'd appreciate additional insights: @ezimanyi @plumpy

fix(config): fix anonymous Google storage credentials

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudAddBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudBakeryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudEditBakeryDefaultsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/huaweicloud/HuaweiCloudEditBaseImageCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/huaweicloud/HuaweiCloudAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/huaweicloud/HuaweiCloudBakeryDefaults.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/huaweicloud/HuaweiCloudBaseImage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/huaweicloud/HuaweiCloudProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/huaweicloud/HuaweiCloudAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/huaweicloud/HuaweiCloudBakeryDefaultsValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/huaweicloud/HuaweiCloudBaseImageValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/huaweicloud/HuaweiCloudProviderValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Relevant Spinnaker Issues: https://github.com/spinnaker/community/issues/17

feat(huaweicloud): first commit for huaweicloud

---

Dockerfile.local

And clean up the Dockerfile a little while I'm in there.

fix(container): Fix the slim container

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Accompanies this [Deck PR](https://github.com/spinnaker/deck/pull/7804)

config(core): Remove MPTV2 UI feature flag

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/DeploymentConfigurationValidator.java

This was accidentally removed in #936.

fix(versions): reenable version checking

---

Dockerfile.local
Dockerfile.ubuntu

Fixes spinnaker/spinnaker#5265

chore(containers): Upgrade the bundled tools

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudAddBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudBakeryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudEditBakeryDefaultsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudEditBaseImageCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/tencentcloud/TencentCloudAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/tencentcloud/TencentCloudBakeryDefaults.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/tencentcloud/TencentCloudBaseImage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/tencentcloud/TencentCloudProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/tencentcloud/TencentCloudAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/tencentcloud/TencentCloudBakeryDefaultsValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/tencentcloud/TencentCloudBaseImageValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/tencentcloud/TencentCloudProviderValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Add TencentCloud account configuration support to Halyard.
Tencent Cloud Provider Proposal:
https://github.com/spinnaker/governance/issues/79

feat(provider/tencentcloud): Add TencentCloud account configuration support to Halyard

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

This reverts commit 759e98840f7d67ec5b2e692a51cb6d8d0cadef56.

Revert "config(core): Remove MPTV2 UI feature flag (#1510)"

---

build.gradle
gradle.properties
gradle/init-publish.gradle

Reverts spinnaker/halyard#1579
This broke the build: https://builds.spinnaker.io/job/Build_PrimaryArtifacts/5190/artifact/logs/build_halyard-command-8559.log

Revert "chore(build): Remove init-publish script"

---

gradle.properties
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/persistentStorage/S3Validator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

I'll wire all of these up to the bumpdeps action, but I'd like to test these larger jumps first to make sure they go okay...

chore(deps): bump internal spinnaker dependencies

---

Dockerfile.compile

This fixes part of spinnaker/spinnaker#5740.

fix(compiler): set the version when using Dockerfile.compile

---

gradle.properties
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

Bump CD to latest and fix CF credentials validator.

fix(halyard): bump CD to 5.61.0 and fix CF credentials validator

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisEditMasterCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisMaster.java

Fixes https://github.com/spinnaker/spinnaker/issues/5847

feat(travis): Support for numberOfJobs and buildResultLimit

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/StatsValidator.java

This has been bothering me for a while. Fixes:

fix(logs): do not print ??? when stats enabled

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/tencentcloud/TencentCloudEditBakeryDefaultsCommand.java

Edit field descriptions in Tencent Cloud bakery command.

fix(docs): edit field descriptions

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisEditMasterCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisMaster.java

Depends on https://github.com/spinnaker/igor/pull/790

feat(travis): Support for filteredRepositories parameter

---

gradle.properties
halyard-config/halyard-config.gradle
halyard-deploy/halyard-deploy.gradle

Also updated some modules to add clouddriver-api dep so that it would still compile.

fix(dependencies): update clouddriver

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Repositories.java

Hi,
This should be fixing https://github.com/spinnaker/spinnaker/issues/5995.
I have tested it in our pre-production environment and it works.
Thanks,

fix(5995): Fix non-existent nexus node in halyard config

---

gradle.properties
halyard-config/halyard-config.gradle
halyard-deploy/halyard-deploy.gradle
halyard-web/halyard-web.gradle

Required a few manual changes because of spinnaker/kork#783

chore(kork): update kork

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

Setting added here: https://github.com/spinnaker/clouddriver/pull/5057

feat(kubernetes): Add cacheAllApplicationRelationships to KubernetesAccount

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

Adds parameters for managing raw resources endpoint configuration added to clouddriver in https://github.com/spinnaker/clouddriver/pull/5167

feat(kubernetes): Add parameters for managing raw resources endpoint configuration to Kubernetes account

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/RetrofitConfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java
halyard-deploy/halyard-deploy.gradle
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceInterfaceFactory.java

This is related to https://github.com/spinnaker/spinnaker/issues/6307

fix(dependencies): okhttp update due to clouddriver upgraded to 5.71.0

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryProviderValidator.java

chore(cloudfoundry): Adds client config properties to CloudFoundryProvider
Related PR: https://github.com/spinnaker/clouddriver/pull/5323/files

chore(cloudfoundry): Adds client config properties

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/bitbucket/BitbucketAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/bitbucket/BitbucketEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/bitbucket/BitbucketArtifactAccount.java

Support Bitbucket Server personal access token

feat(artifacts/bitbucket): add token auth credentials support

---

.mergify.yml

and are causing auto-merging to hang

chore(build): remove mergify conditions that don't get satisfied

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.slim
Dockerfile.ubuntu

Motivation:
Allow running & experimenting with Spinnaker locally on Macbok M1.
Relevant docs:
https://github.com/docker/build-push-action/blob/master/docs/advanced/multi-platform.md
Similar MR:
https://github.com/spinnaker/rosco/pull/886

chore(build): Build docker images for multiple architectures

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureProvider.java

We replaced json templates with hcl in azure
https://github.com/spinnaker/rosco/pull/910

config(azure): changing default bake template

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java

https://github.com/spinnaker/spinnaker/issues/6881#issuecomment-1725442790

fix(java17): add options for java11 image variants
