halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/kubernetes/DockerRegistryReference.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/ValidateFieldRegex.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/providers/ValidateAccountName.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/UpdateableSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/providers/AccountSpec.groovy

Introduces regex-field validation & provides an example on account names. @ttomsu or @jtk54 PTAL

Validate account name by regex

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Halconfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/ValidateField.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/ValidateFieldRegex.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/ValidateNotNull.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/Validator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/providers/ValidateAccountName.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/providers/ValidateFileExists.java

`@` annotations aren't punctuated when they refer to a class/method/exception/field.

Add doxygen style comments

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/FieldReference.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Reference.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/Updateable.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/validate/v1/Validator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/UpdateableSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/model/v1/providers/AccountSpec.groovy

This is necessary for validations that occur across accounts, i.e. Kubernetes depends on Docker Registries.
@duftler @ttomsu @jtk54 PTAL

Allow validation based on halconfig context

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/errors/v1/HalconfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/errors/v1/HalconfigFixableIssue.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/errors/v1/config/IllegalConfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/errors/v1/config/NoConfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/errors/v1/config/ParseConfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/model/v1/providers/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/services/v1/ConfigService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/services/v1/DeploymentService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/errors/v1/HalconfigExceptionHandler.java

@duftler or @jtk54 or @ttomsu PTAL
Spring by default only shows the `message` an exception was instantiated with and thrown when handling a response. I added a `HalconfigExceptionHandler` to catch all `HalconfigException`s and return the `errors` & `warnings` they contain.

Propagate errors & warnings to client

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/Updateable.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/Validator.java

The `@throws UnrecognizedPropertyException` was an error after I removed it from the method signature. The others were all warnings due to missing descriptions or properties.
@duftler (another quickie, barring any spelling/grammar errors)

Fix javadoc build errors & warnings

---

halyard-cli/halyard-cli.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ShowCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/Color.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/Ui.java

I'm breaking the actual communication with the daemon into the next PR, but this enables commands like
```
hal config show --provider=kubernetes
hal -v --color=false config
hal --help
```
etc, etc...
@duftler @ttomsu @jtk54 PTAL

(cli) added command parsing framework

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/HalconfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/HalconfigFixableIssue.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/config/NoAccountException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/config/NoConfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/config/NoProviderException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/GoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/GoogleProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/NamingService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/errors/v1/HalconfigExceptionHandler.java

@duftler or @ttomsu or @jtk54 or @ewiseblatt PTAL
Don't pay too much attention to the `NamingService`, halfway through I realized it would be better to add fields to the issues & warnings describing exactly which account/provider/field is affected, but that would bleed to far into my refactor of the `FixableIssues`.

Flushed out provider & account endpoints

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/kubernetes/KubernetesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiParagraphBuilder.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/ValidatorCollection.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java

The client builds the account object for a specific provider, and sends it to the daemon for validation. If it passes, the halconfig is updated.
@duftler or @jtk54 or @ewiseblatt or @ttomsu PTAL

add-account command implemented for k8s

---

README.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractDeleteAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/providers/AbstractHasAccountCommand.java

This makes commands that require account-name easier to write, i.e.
```
hal config provider kubernetes add-account my-k8s-account --context my-context
```
vs.
```
hal config provider kubernetes add-account --account-name my-k8s-account --context my-context
```

Remove --account-name parameter when it's required

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/DeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-deploy/halyard-deploy.gradle
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/component/v1/Clouddriver.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/component/v1/ComponentService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/component/v1/ComponentType.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/component/v1/ServiceFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/DeployConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/job/v1/JobExecutor.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/job/v1/JobExecutorLocal.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/job/v1/JobRequest.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/job/v1/JobStatus.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/Provider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/service/v1/DeployService.java
halyard-deploy/src/main/resources/kubernetes/raw/hal-clouddriver.yml
halyard-web/halyard-web.gradle
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

This isn't functional yet, but with the addition of a new JobExecutor this PR was starting to grow a little too large.
Now Haylard can spin up a clouddriver instance, and open a proxy to the cluster clouddriver was deployed in (assuming kubectl is installed).
@duftler PTAL

First pass at deploying Spinnaker to Clouddriver.

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiUi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/problem/Problem.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/problem/ProblemBuilder.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/problem/ProblemSet.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/problem/ProblemSetBuilder.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

Any field that has a corresponding "fieldName"Options() method will supply alternative entries during validation.
I also updated the formatting of errors to group them by location.
@duftler @jtk54 PTAL

Add support for logging options.

---

build.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/SpinnakerComponent.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/spinnaker/v1/component/SpinnakerComponentSpec.groovy
halyard-deploy/halyard-deploy.gradle
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/ProviderInterface.java

Given that the secrets/volumes will get fairly complicated to create, it's easier to instantiate our kubernetes objects like this.

Use k8s api rather than kubectl to construct objects

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/StrictObjectMapper.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/errors/v1/config/ParseConfigException.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/ValidatorCollection.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/HalconfigParserMocker.groovy
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java

Errors without a problem set causing halyard to fail without an explanation.
The object mapper was also being instantiated incorrectly, using a bean definition from another imported project causing it to ignore unknown properties. @duftler or @danielpeach or @jtk54 PTAL

Fix retrofit error suppression

---

halyard-cli/halyard-cli.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-core/halyard-core.gradle
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-web/halyard-web.gradle
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/errors/v1/HalconfigExceptionHandler.java
settings.gradle

This moves a shared dependency from -web to -core, allowing us to build one jar containing both cli & web entrypoints.

Make core package to compile cli alongwith web

---

build.gradle
halyard-web/halyard-web.gradle

This should (in theory) create startup scripts in the debian to run halyard in two modes.

Create new startup scripts

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java

This makes reading the command's help a little easier, as well as pulls `--help` into a global parameters (which it is).

Sort help & subcommand flags

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/resources/hal-completor-body
halyard-cli/src/main/resources/hal-completor-case
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/resource/v1/JarResource.java
halyard-web/pkg_scripts/postInstall.sh

This doesn't (yet) do fancy things like ask the daemon for options, but generates completion help for all statically known subcommands & flags. If you're interested in how it works, read [this](https://debian-administration.org/article/317/An_introduction_to_bash_completion_part_2).

Adds basic tab-completion support to halyard

---

halyard-web/pkg_scripts/postInstall.sh

1. Overwrite rather than append to command-completion & wrapper scripts
2. Use tee rather than pipes to write command completion

Two fixes to debian installer scripts

---

halyard-web/halyard-web.gradle

@ttomsu @lwander PTAL
actions in the gradle build should run in a task, the calls to startScripts I think were happening during a couple phases of the buildscript interpretation
setting mainClassName on the project will make the default startScripts call generate the script/application for that and then adding another CreateStartScripts task spits out the cli script.
confirmed that the resulting distZip / distTar only has one copy of each

fix script generation

---

halyard-web/pkg_scripts/postInstall.sh

This is currently the wrong approach - the completion is only sourced in the shell running the installer. I'm not sure what the right approach is yet, but right now the install is broken.

Remove postInstall bash completion

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authn.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Security.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Ssl.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/EndpointFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerEndpoints.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/DeckProfile.java
lombok.config

https://github.com/spinnaker/halyard/issues/108
This is the smallest amount of work needed to get Deck to read Gates new public URL by adding support for SSL configuration & public UI + API addresses. @ttomsu and I figure it's best to do TLS across all the Spinnaker services (when it's enabled) so it's an all-or-nothing approach there.

Start of halyard config security

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/PersistentStorage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authn.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ConfigService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/LookupService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ValidateService.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/HalconfigParserMocker.groovy
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/TaskController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java

There was a corner case preventing validators from using the lookup
services, since they would implicitly load from disk rather than
validate what had been modified in memory. This was caught in the
edit-storage command which would rely on the account lookup service to
check that the specified account was of the correct type.
This is fixed by making the halconfig thread local to any task or 
operation that needed to edit it. 
@duftler PTAL

Make the halconfig thread local

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/resources/hal-completor-body
halyard-cli/src/main/resources/hal-completor-case

Now that some commands share names, the bash completion logic needed to
walk the list of commands and recursively match on the NestableCommand
object.
Here's the output https://gist.github.com/lwander/61d934135da10715055b7b13ddc37f56

Dedup bash completion

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/DeployConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/RunningServiceDetails.java

This enables 2 things:
1. Diffing when applying new config changes to your installation.
2. Inspecting your running cluster without recomputing endpoints

Backup generated config

---

halyard-web/etc/init/halyard.conf

This is (unfortunately) needed for halyard to install debians on behalf of the user.

Fix halyard init entry to run as root

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/AdminCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishBomCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/admin/PublishProfileCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerArtifact.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/registry/WriteableProfileRegistry.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/registry/WriteableProfileRegistryConfig.java
halyard-web/config/halyard.yaml
halyard-web/config/halyard.yml
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AdminController.java

With the following spring config:
```yaml
spinnaker:
config:
input:
writer: true
bucket: halconfig
```
Halyard can now do the following:
```
$ hal admin publish bom --bom-path /a/b/c/bom.yml
$ hal admin publish profile clouddriver --bom-path /a/b/c/bom.yml --profile-path /x/y/z/profile.yml
```

Add admin support for halyard

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/DeployCommand.java

@lwander 
The line with the added period was the only top-level help description without one.

style: adds missing word + punctuation

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/PersistentStorageValidator.java

Unfortunately I got stuck on spinnaker's AWS credentials handling. Nonetheless, it sets up the pattern for validating front50 s3 config, as well as the pattern for other providers.

A step towards s3 front50 support

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/resources/debian/install.sh

Packer installation is now handled by rosco debian. Config path is needed to configure apache.

Remove packer installation, provide install with config path

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/VersionsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/versions/BomVersionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiFormatUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/VersionsService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java

Needed for Spinnaker release promotion.

Provide user with BOM when asked

---

README.md

Looks like the executable flag isn't preservered by github's raw user content.

Install requires bash

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/appengine/AppengineAccountValidator.java

@lwander please review.
If the region isn't set on the credentials, the credentials will try to look up the App Engine region associated with the credentials, which will fail if the user hasn't yet deployed an application to App Engine.

fix(appengine) prevent bad API call

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/SecurityCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AbstractAuthnMethodCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AbstractAuthnMethodEnableDisableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AbstractEditAuthnMethodCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnMethodCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnMethodEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/EditOAuth2Command.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/OAuth2Command.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/AbstractEditRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/AbstractEnableDisableRolesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/AbstractRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/EditGoogleRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/EditRolesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/EnableDisableRolesCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/GoogleRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/RolesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/RolesProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authz.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/GoogleRoleProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/GroupMembership.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/RoleProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/SecurityService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/GoogleRoleProviderValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/FiatProfile.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SecurityController.java

Only supports google, and doesn't validate yet. I also need to prevent fiat from being deployed if it's not enabled.

feat(config): Fiat config generation + CLI commands

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/RunDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/RemoteAction.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/BillOfMaterials.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/WriteableProfileRegistry.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/resource/v1/TemplatedResource.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentDetails.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DeploymentFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/FlotillaDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalhostDebianDeployment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/provider/v1/kubernetes/KubernetesProviderInterface.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/resources/debian/install.sh
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

@ttomsu This will let you install all the spinnaker components without configuring them, for the purpose of baking images. You just need to run
`sudo hal deploy run --no-validate --install-only`
after picking a valid version.

feat(halyard) Debian-only install

---

InstallHalyard.sh
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditDeploymentEnvironmentCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
services/vault/config/vault.hcl
services/vault/install/install.sh
services/vault/policies/halyard.hcl
services/vault/policies/spinnaker.hcl
services/vault/startup/read-config.py
services/vault/upstart/vault.conf

This does the following:
1. Install the vault binary alongside Halyard.
2. Provides instances a startupscript to pull config into their filesystem.
3. Provides a sample vault + policy setup.

feat(deploy): Configure vault secret storage

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/MetricStoresCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/AbstractEditMetricStoreCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/AbstractMetricStoreCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/AbstractMetricStoreEnableDisableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/EditMetricStoresCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/MetricStoreCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/MetricStoreEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/datadog/DatadogCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/datadog/EditDatadogCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/prometheus/EditPrometheusCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/prometheus/PrometheusCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/stackdriver/EditStackdriverCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/stackdriver/StackdriverCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/metricStores/datadog/DatadogStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/metricStores/stackdriver/StackdriverStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/MetricStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/MetricStores.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/MetricStoresService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MetricStoresController.java

feat(cli): Configure metric stores via CLI

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditSecurityCommand.java

When setting api domain using `hal config security edit`, it sets the ui address instead

fix(cli): Set api domain

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProviderSpec.groovy

Prior to this fix PrimaryAccount would not be correct if the account it referred to was removed.
@duftler this removes the TODO you added during rosco validation.

fix(config): PrimaryAccount behavior

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractHasAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/resources/hal-completor-body
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/AccountService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/OptionsService.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonOptions.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java

Halyard can now present options for `--flags` dynamically. See below how I read docker registries from the halconfig, and context options from the kubeconfig.

feat(cli): context-sensitive bash completion

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerRuntimeSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/debian/DebianServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/debian/DebianVaultClientService.java
halyard-deploy/src/main/resources/debian/install.sh
halyard-deploy/src/main/resources/services/vault/install.sh
services/vault/startup/google/mount-config.sh
services/vault/startup/mount-config.py
services/vault/startup/mount-config.sh

Everything is now in place for building GCE service-specific VM images.
You'll need to run the following:
```
hal deploy actuate --omit-config --no-validate --service-names $COMPONENT monitoring-daemon vault-client consul-client
```
As well as copy the directory `./services/vault` into `/opt/spinnaker/`, since we'll be calling `/opt/spinnaker/startup/mount-config.sh` as the startup script.

feat(deploy): Install vault using BOM version

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/kubernetes/KubernetesDistributedService.java

This morning @skim1420 suggested scaling down each subcomponent during a red/black to save on resources. It makes sense & reduces update complexity significantly.

feat(deploy): Always scale down distributed services on deploy

---

halyard-cli/src/main/resources/hal-completor-body

The child task PR increased task log output that should have been silenced when retrieving field options.

fix(cli): Options were including task output

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/problem/v1/ProblemSet.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java

Errors were only being set when task status was retrieved, not when the task completed. Also, the call to  `reduceChildren` was ignored in the parallel deploy.

fix(deploy): Propagate error from parallel child task

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/util/ValidatingFileReader.java

Turns out some systems will put the permission denied error in the `FileNotFoundException`, while others put it in the `IOException`.

fix(daemon): Add no access remediation to FileNotFoundException

---

InstallHalyard.sh

Depending on how sudo was configured, env vars aren't persisted when running `sudo`. Getting the user with `who` gets around that problem.

fix(install): Sudo-independent run-as-user

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/BakeDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/BakeService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/BakeServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianVaultClientService.java
halyard-deploy/src/main/resources/debian/pre-bake.sh

This ensures services are started in order of priority (e.g. vault, then consul, then component). No changes needed on your part @jtk54

feat(bake): Bake top-level startupscript into VM images

---

halyard-deploy/src/main/resources/debian/pre-bake.sh

My test env already had this directory, but the fresh VMs don't.

fix(deploy): Fix startup behavior

---

InstallHalyard.sh

This is not permanent, but fixes nightly VM builds until we better
segregate which of our build tasks require which halyard release track
(all currently assume `nightly`).

chore(install): Make `nightly` the default release track

---

halyard-cli/.gitignore
halyard-cli/Makefile

@lwander  - You were right that you can't modify the parent shell from within Make, so I just printed a command the user can copy/paste to enable autocomplete during development.

chore(autocomplete): Adds small Make task for non-installed autocomplete

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/DeploymentEnvironmentCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/FeaturesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/MetricStoresCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/PersistentStorageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/SecurityCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/VersionConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/AbstractNamedCiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/master/AbstractGetMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/metricStores/MetricStoreCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/AbstractNamedPersistentStoreCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractNamedProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/bakery/AbstractGetBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/api/ApiSecurityCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/api/SpringSslCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnMethodCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/GoogleRoleProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authz/RolesCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/ui/ApacheSslCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/FormatConverter.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/DetailsDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/versions/BomVersionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/versions/LatestVersionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/versions/ListVersionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/OperationHandler.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/ui/v1/AnsiFormatUtils.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java

This is needed for our nightly image cleanup, since we need to parse which images don't belong to any released, stable version of Spinnaker.

feat(cli): Add -o for output formatting

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth/EditOAuthCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth/OAuthCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/converter/OAuthProviderTypeConverter.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Authn.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/AuthnMethod.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/OAuth.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/SecurityService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/OAuthValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringConfig.java

I left references to "OAuth 2.0" in the doc lines.

chore(oauth): Change command from oauth2 to 'oauth' for simplicity

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/task/ListTaskCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/OperationHandler.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/ResponseUnwrapper.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/TaskKilledException.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonEvent.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskHandler.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTaskInterrupted.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/ShallowTaskList.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/TaskRepository.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/TaskController.java

Tasks now timeout (no matter what), deleting their execution and terminating parent/child tasks. This timeout is configurable when submitting the task and defaults to 1 minute for top-level tasks, or the timeout of the parent task where applicable.

feat(core): Timeouts

---

README.md
halyard-web/halyard-web.gradle
install/InstallHalyard.sh.gen
install/generate.sh
install/nightly/InstallHalyard.sh
install/stable/InstallHalyard.sh

It looks like the same file was checked in 3 times, but 2 are auto-generated based on the 3rd each time you invoke `./gradlew`

chore(install) auto-generate install scripts for release tracks

---

install/InstallHalyard.sh.gen
install/nightly/InstallHalyard.sh
install/stable/InstallHalyard.sh

@jtk54 
You now want to grab the install script from the new location as shown here: https://github.com/spinnaker/halyard#installation
Run with `--repostory <url> --spinnaker-repository <url>` set (both `<url>`s should be identical in our case).

chore(install): Surface Halyard config flags in install script

---

docs/commands.md
halyard-backup/halyard-backup.gradle
halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/services/v1/BackupService.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/BackupCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/backup/CreateBackupCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverBootstrapProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/FiatProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/IgorProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/ApacheSpinnakerProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java
halyard-web/halyard-web.gradle
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/BackupController.java
settings.gradle

This feeds into a KMS story for remote backups.
Right now it takes your entire halconfig, determines all files it needs, and copies it and the files into `~/.hal/.backups/`, rewriting properties as needed.

feat(backup): Support for config backups

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConsulClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerMonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianConsulClientService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/SidecarService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/ResourceBuilder.java

In the process I found that an update to kubectl caused contention when running multiple parallel proxies, this is fixed here as well by associating thread IDs with open connections to ensure no proxy is shared across Halyard Tasks.

refactor(deploy): Dynamically associate sidecars

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleGateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java

gcloud was spawning a subprocess that java couldn't kill, leading to a large number of leaked processes

fix(deploy) Switch to `ssh` from `gcloud ssh`

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java

I recently switch from Gson to Jackson to act as Retrofit's deserializer, which can't serialize types that have references to generic types. By instead having the interface deal only with `Object`s, and having `Daemon.java` convert the type directly, we avoid this problem.

fix(cli): Rely on ObjectMapper to convert types

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java

This now waits for the connection to open correctly, as well as uses a "halyard-only" ssh keypair for your instances

feat(deploy): Improve SSH tunnel handling for GCP

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianMonitoringDaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesMonitoringDaemonService.java

This isn't complete, since the monitoring config folder isn't pointing at the expected /opt/spinnaker-monitoring/config/, but instead /opt/spinnaker-monitoring making it difficult for k8s to mount spinnaker-monitoring.yml. This will either take change to spinnaker/spinnaker-monitoring or the config mounting in halyard. I'm talking to @ewiseblatt about it.

feat(deploy): Multi VM monitoring

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/PersistentStorageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/oraclebmcs/OracleBMCSCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/oraclebmcs/OracleBMCSEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oraclebmcs/OracleBMCSCommandProperties.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/PersistentStorage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/PersistentStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/OracleBMCSPersistentStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PersistentStorageService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/persistentStorage/OracleBMCSValidator.java

This adds support to Halyard for configuring front50 to use Oracle's Object Storage Service.

feat(oraclebmcs): Add Oracle BMCS persistent storage configuration

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/DeploymentConfigurationValidator.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/AtomicFileWriter.java

I was going to add generic support for notifications, but realized that different kinds of notifications merit different treatment, and didn't want to hard-code all of those, or come up with something robust enough to handle all of our future notification worries. So instead I'm going to be splitting up the notification work into three categories:
1. Spinnaker update available: Addressed here, see below screenshots.
2. Halyard update available: Will be addressed similar to how it was done here.
3. Critical spinnaker announcement: I can only think of security-style patches that need to be applied by the Halyard operator, and therefore think that special cases of 1 & 2 are more appropriate.

feat(validate): Version mismatch warning

---

AUTHORS
docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/s3/S3EditCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/S3PersistentStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/persistentStorage/S3Validator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/aws/AwsAccountValidator.java

#116: Add validation for AWS accounts and S3 persistent storage. The S3 bucket validation will create the bucket if it does not exist (this makes the S3 validation behave in the same way as the GCS validation).

feat(validation): Add validation for AWS accounts and S3

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/job/v1/JobExecutorLocal.java

You will probably want to supply narrower capture level than `--log all` to the CLI

chore(logs): Reduce job poll log level from info to debug

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/DeploymentConfigurationValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/HalconfigValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/validate/v1/HalconfigValidatorSpec.groovy
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/memoize/v1/ExpiringConcurrentMap.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java

This introduces an `ExpiringConcurrentMap` to allow us to memoize with a short timeout a lot of the duplicate requests for Halyard versions.

feat(core): Warn if halyard version out of date

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/s3/S3EditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/S3PersistentStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/persistentStorage/S3Validator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/aws/AwsAccountValidator.java

Second take at implementing validation of AWS accounts and S3 buckets. Please take a look @lwander  @ewiseblatt.
It kind of supports the assumeRole, and you can set credentials in the cli. It's not properly tested, so expect the unexpected. I just wanted to get it out there and collect some feedback.

feat(validation): Support AWS assumeRole and setting credentials at the command line

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/AwsCredentialsProfileFactoryBuilder.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java

Keygen only seems to work from our host machines due to how gce sets up
remote host authentication

fix(deploy): Multi vm keygen

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/DeploymentConfigurationValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/HalconfigSpec.groovy

The behavior is now: A user can configure spinnaker w/o a versioned picked, but once they deploy it will fail.

feat(version): No default spinnaker version

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java

Rendering of the command reference was incorrect on the docs page. This separates subcommands from the parameter bullet list.

docs(spacing): Fix spacing

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/persistentStorage/S3Validator.java

`new S3Config().s3StorageService(s3Client, s3Properties);` calls `s3StorageService.ensureBucketExists();`, so no need to do it again.
Added bonus: the catch clause actually catches exceptions.

Don't validate/create S3 bucket twice

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianDeckService.java

When I use the `$HOME/.hal/default/service-settings/deck.yml` file to bind to port 80, I'm unable to connect to Spinnaker site.
The default enabled `000-default.conf` file in the apache2 binds to port 80 and this has precedence over `spinnaker.conf` file.

fix(deploy): Local debian shows default site when bound to port 80

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckDockerProfileFactory.java

This fixes an issue where the `authEnabled` property is not set when authentication is enabled in Halyard. 
If `authEnabled` is not set properly when `authn` is enabled, the Deck UI doesn't work properly (failure to redirect to login page, missing user banner, etc,.).

Enable authentication in deck when authn is enabled

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesProviderUtils.java

When possible, orca & rosco will be scaled down during deployments (if they aren't handling any work).

feat(deploy): Scale down orca & rosco during deploys

---

halyard-web/pkg_scripts/postInstall.sh
install/InstallHalyard.sh.gen
install/nightly/InstallHalyard.sh
install/stable/InstallHalyard.sh

There are duplicate changes to the install script, because the InstallHalyard.sh.gen generates (with some small templating) the other two InstallHalyard.sh files.
By first setting halyard-user (before Halyard is installed) we can be sure that the log dir can be correctly assigned on both installs & updates of Halyard.

fix(install): Use halyard-user to assign ownership to log dir

---

install/InstallHalyard.sh.gen
install/nightly/InstallHalyard.sh
install/stable/InstallHalyard.sh

The `start halyard` command was breaking the install path after the
`postInstall.sh` now correctly starts Halyard after it's installed.

fix(install): Remove unneeded "start halyard" after install

---

halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/services/v1/BackupService.java

Several users have now seen the backup controller fail to create a tar archive due to unclosed entries with fairly simply hal config directories. I haven't been able to reproduce this error, but my best guess is that archive entries created for any directory are causing grief for their local tar archiver. Reading [the spec](https://commons.apache.org/proper/commons-compress/apidocs/org/apache/commons/compress/archivers/tar/TarArchiveOutputStream.html#closeArchiveEntry--) it could (?) be interpreted that only entries with data can be closed.

fix(backup): Only close archive entries with data

---

docs/commands.md
halyard-cli/daemon-halyard
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/Main.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/GlobalOptions.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
install/debian/InstallHalyard.sh
release/all.sh
release/debian.sh
release/publish.sh
startup/debian/hal

The idea is:
1. We package up the JARs & generated wrapper scripts built by gradle
2. Users download that package as well as a script that starts the daemon when it's not running yet
Each system will need to supply a script to download java8, as well as provide a script to start the daemon when it's not running.

chore(install): New install path

---

release/all.sh

Useful for things like relasing version x.y.z as well as "latest"

chore(release): Specify multiple release versions

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesProviderUtils.java

This gracefully handles a mix of nu & old orcas by only disabling (and then flagging for either deletion or scaling down depending on the age) orca instances that implement the new `/admin/instance/enabled` endpoint. All other orcas are untouched & reported as "unkillable". See sample behavior here:

feat(deploy): Disable nu-orca instances during deploy

---

AUTHORS
docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackAddBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackBakeryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackBaseImageCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackEditBakeryDefaultsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackEditBaseImageCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackBakeryDefaults.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackBaseImage.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/BakeryService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackBakeryDefaultsValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackBaseImageValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackProviderValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Adding Openstack Bakery commands to halyard
h/t @shazy792 @dylanbernhardt @matthewkohner @msilpala

Adding openstack bakery (#3)

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ValidForSpinnakerVersion.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/FeaturesService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/FieldValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/ValidatorCollection.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java

Pipeline template feature flag / 'ValidForSpinnakerVersion' annotation.

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/openstack/OpenstackBakeryDefaultsValidator.java

Finally got our bakes working and found domainName to be required as well, so just some final (simple) validation.

Adding simple validation for domainName

---

Dockerfile
Dockerfile.local

The halyard container image needs the kubectl command for setting up distributed environments.
It was missing from the default setup and needs to be installed afterwards, which can be PITA when repeatedly running it.
I installed it inside to have it available without additional work.

Install kubectl inside the container image

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedServiceProvider.java

https://github.com/spinnaker/halyard/pull/654 introduced a bug where the clean command would not accept a user defined deploy location.

fix(halyard/KubernetesDistributedService): Clean Command

---

halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy

Includes a quick set of SAML properties, and a first property (commented out) with which to test-drive the LDAP implementation that my Target peeps are working today.
Technically, we could merge this now and fill in the rest of the properties in separate PR's. But I prefer not to merge commented-out stuff to master.

[WIP] Add examples for some authn properties.

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaBootstrapProfileFactory.java

fix(pipeline_templates): disable pipeline templates for orca-bootstrap

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaService.java

When kubernetes returns a 503 for a non-existent service, retrofit tries to cast the error message into that of the original response body type.

fix(deploy): Fix deserialization bug showing strange errors

---

halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ProvidersSpec.groovy

READ FIRST.
I beefed up the ProvidersSpec to validate that _all_ current providers show up as children in the iterator. 
In addition, I restructured the spec to be a little more groovy and a little less iffy. But I couldn't decide _which_ of two structures to go with. So I'm interested in @lwander's opinion and preference. See the comments above each method for high-level descriptions of why you might prefer one or the other.

Validate all Providers in ProvidersSpec.

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java

Due to https://github.com/spinnaker/orca/pull/1548, the profile stanza is now
in plural form and not single form as it used to.

refactor(pipline_templates): update orca profile to pipelineTemplates

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java

To support old versions of orca, it is needed to append also the singular form and not just the plural.
#664

fix(config/orca): append singular form and plural form of pipelineTemplates

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/AuthnMethodEnableDisableCommandBuilder.java
halyard-cli/src/test/groovy/com/netflix/spinnaker/halyard/cli/command/v1/CommandTreeSpec.groovy

Here's a proposed structure for wrapping some specs/tests/documentation around how all the subcommands are structured. While making it I discovered and fixed a duplicated =subcommands= member in HalConfig.
Most of our little team at Target has given this a thumbs-up. Looking to @lwander for opinions and suggestions.

CLI Specs: first cut

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AdminController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/BackupController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/BakeryController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/CiController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ClusterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ConfigController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentEnvironmentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MasterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MetricStoresController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SecurityController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java

Per Joshua Bloch's description in "Effective Java", required fields of
a builder should be compile-time required.
Context - this ticket:
https://github.com/spinnaker/halyard/issues/617
Appears to have been allowed because a required field was missing
during a large refactor:
https://github.com/spinnaker/halyard/pull/283

Make buildResponse a required field of StaticRequestBuilder

---

README.md

It's not obvious that the github docs are non-exhaustive
and that the main docs are actually elsewhere

docs: link to spinnaker.io docs for halyard

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/x509/EditX509Command.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/X509.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/X509Validator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/X509Config.java

Forgot to make docs for these commands in the last PR so I ran it this time.

feat(authn): Add subjectPrincipalRegex edit option to x509 command

---

README.md
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/CustomSizing.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/ResourceBuilder.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/KubernetesDistributedServiceSpec.groovy
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/ResourceBuilderSpec.groovy
halyard-web/halyard-web.gradle

see spinnaker [issue 683](https://github.com/spinnaker/halyard/issues/683)

feat(deployments): allows for custom sizing for kubernetes distrbuted deployments in halconfig

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/AbstractEditProviderCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dcos/DCOSAccount.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java

Quick fix for a the loudest of the warnings that come up when building halyard.
The deprecated member seems to only be used in one place, where it is set. So removing it should have no functional effect.
The two @EqualsAndHashCode changes only make explicit what is already being built. If these _should_ be calling super, then we have a sneaky bug in the current master.

fix(build) Fix build warnings

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/travis/TravisEditMasterCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisMaster.java

Support the new configuration field (https://github.com/spinnaker/igor/pull/193)

feat(travis): Add numberOfRepositories configuration

---

install/Installer.sh

The `-a` arg is missing in the usermod command. When I run the installer on Ubuntu 14.04, this replaces all of my user's groups with just `spinnaker`. 
Adding the `-a` argument so that the `spinnaker` group is appended.

Fix usermod group append in Installer.sh

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Update halyard command line to enable/disable canary feature flag in deck settings.js
hal config features edit --legacyCanary false
hal config features edit --legacyCanary true

feat(legacyCanary): feature flag for legacy canary support

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GoogleProfileRegistry.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GoogleWriteableProfileRegistry.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/ProfileRegistry.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/WriteableProfileRegistryConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/ArtifactService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RegistryBackedArchiveProfileBuilder.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RegistryBackedProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfileFactory.java

It was a bad idea to give the profile storage the ability to read anything with 'getObjectContents', since not all interfaces will be able to satisfy that. This is the first step in cleaning that up.

refactor(profiles): fixup bad decision around profile storage

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/EchoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/FiatService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/Front50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/IgorService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaBootstrapService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/RoscoService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpringService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/git/LocalGitClouddriverService.java

feat(localgit): write config to ~/.spinnaker where possible

---

halyard-deploy/src/main/resources/debian/init.sh

This service allows starting and stopping all spinnaker services with a invocation of service.

feat(xenial_builds): Add Systemd configuration for parent service

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianService.java
halyard-deploy/src/main/resources/debian/install.sh

Apache start is failing to pick up the site if its newly enabled.
Also fixing stop command that is failing with: "stop: Unknown instance:" since it is executing "service stop", instead of the intended "service apache2 stop".

bug(click_to_deploy): 1.5.2 click to deploy not properly restarting apache

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/github/GitHubAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/github/GitHubArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/github/GitHubArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/github/GitHubEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/github/GitHubArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/github/GitHubArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ArtifactProviderService.java

Allows Halyard to configure clouddriver to download artifacts from GitHub, see https://github.com/spinnaker/clouddriver/pull/2231

feat(artifacts): Add support for GitHub artifact account

---

install/debian/InstallHalyard.sh

In the jar based installation, first check to make sure the debian package is not installed. If it is, provide a link to the user to migrate.

feat(halyard_installation): Prevent accidental second install.

---

install/debian/InstallHalyard.sh

It seems that Amazon Ubuntu 14.04 doesn't have "hash", but which returns equal error codes and is present in more places it seems.

bug(halyard_install): Prevent install failure if no hash.

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/GlobalApplicationOptions.java

Halyard daemon is failing to start due to not gracefully handling missing properties configuration.

bug(missing_halyard_properties): Handling missing properties file.

---

install/debian/InstallHalyard.sh

set -e causing execution to stop after detecting halyard is not already installed.

bug(fix_halyard_installer): Fix installer script.

---

halyard-deploy/src/main/resources/git/prep-component.sh

If we run `git remote add upstream` when `upstream` already
exists, we get the annoying output `fatal: remote upstream already exists.`
for every component.
Run `git remote remove upstream` first to avoid printing this error.
This also mimics the behavior of the newer git command `git remote
set-url` that we use when git is above a certain version.

fix(localgit): Remove and then add git remote

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/GlobalApplicationOptions.java

This is not a complete solution yet, but this seems to correct one of the issues I'm seeing when running a local halyard on macOS.
Still getting this error when trying to set the version via CLI:
```
$ hal config version edit --version 1.5.4
+ Get current deployment
Success
- Edit Spinnaker version
Failure
Problems in Global:
! ERROR Unexpected exception: java.lang.NullPointerException
- Failed to update version.
```
Meanwhie, the daemon spits this out to its console:
```
2018-01-19 17:58:57.182  WARN 37078 --- [       Thread-6] c.n.s.h.core.tasks.v1.TaskRepository     : Task [Edit Spinnaker version] (56525576-c51a-4d43-825c-499d5a0e1595) - RUNNING failed with unexpected reason: 
java.lang.NullPointerException: null
at com.netflix.spinnaker.halyard.core.DaemonResponse$UpdateRequestBuilder. …
```

Create a default GlobalApplicationOptions instance if no config file.

---

halyard-deploy/src/main/resources/git/prep-component.sh

The remote "upstream" might not exist. Do not fail if so.
fixes bug introduced in https://github.com/spinnaker/halyard/pull/818

fix(localgit): Do not fail if removing git remote fails

---

halyard-cli/Makefile

@lwander 
Without something like this, I cannot build a release branch because of nebula constraints.

fix(gradle): useLastTag to appease nebula on spinnaker branches.

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/DaemonResponse.java

I'm not sure if this is correct "long term" fix, but it at least allows us to run requests that don't have a "clean" step specified.

fix(core): Fix NPE when no clean step provided

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditDeploymentEnvironmentCommand.java

Explain how `--location` is used to specify the k8s namespace Spinnaker
will be deployed to when using k8s as the deployment environment.

docs(halyard_k8s): Add more detail to deploy edit cmd

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommand.java

Was:
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/to
Should be:
https://kubernetes.io/docs/tasks/access-application-cluster/configure-access-multiple-clusters/

Kubernetes URL fixed

---

halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml

The annotations should include the double quotes to make the value a string according to Jackon's rules.
Fixes warnings like
```text
2018-02-17 17:52:38.276  WARN 1 --- [ecutionAction-7] .s.c.k.v.d.m.KubernetesManifestAnnotater : Illegally annotated resource for 'moniker.spinnaker.io/cluster': com.fasterxml.jackson.core.JsonParseException: Unexpected character (''' (code 39)): expected a valid value (number, String, array, object, 'true', 'false' or 'null') at [Source: 'front50'; line: 1, column: 2]`
```
The previous values created `moniker.spinnaker.io/application: '''spin'''`, as could be seen using `kubectl edit -n spinnaker deploy/spin-orca`

Fix moniker annotations

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ClouddriverProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ClouddriverService.java

When deploying to a k8s cluster using gcp (gcloud) as the auth provider,
it was possible that the path set was different from the path provided
inside the clouddriver container. Setting the path here to be `gcloud`
in only the staged kubeconfig fixes this.

fix(kubernetes): fix gcloud binary path

---

halyard-core/halyard-core.gradle
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GitProfileReader.java

Rosco deployment currently fails when halyard is configured as localgit
and is pointed at a non-release branch.  This change updates the way
that haylard reads the rosco profile files in this situation and
addresses the issue.

fix(rosco): Fix localgit rosco deployment when pointing at a branch

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml

When deploying spinnaker to kubernetes, it is sometimes necessary for
some of the services to have extra annotations. For example when using
kube2iam to specify the role certain pods should get. This change adds a
map for podAnnotations to the KubernetesSettings and applies it to both
the replicasets in the v1 provider and the deployments for the v2
provider.

feat(kubernetes): Allow custom pod annotations for spinnaker services

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

When running an unvalidated version of spinnaker, set the changelog
to an empty string so we skip changelog fetching rather than try to
fetch the placeholder {%changelog.gist.id%} from GitHub.

fix(changelog): Stop fetching placeholder changelog

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

Keeping the command hidden, since you have to be building your own BOMs to use this, and I don't want people to be confused.

feat(kubernetes): command support for skins

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1Front50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Front50Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

This is to allow spinnaker to be deployed using the non-root docker images into k8s when managing aws resources.

fix(deploy/aws): mount aws creds in spinnaker home

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/BillOfMaterials.java

kayenta service prior to 1.7 was not enabled, and needs a safe default to lookup instead. @duftler FYI

fix(deploy): fix deploys prior to 1.7

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ClouddriverService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/Front50Service.java

The aws credentials were deduped by name, causing front50 to only mount
one of the spinnaker/root creds
closes https://github.com/spinnaker/spinnaker/issues/2642

fix(deploy/kubernetes): fix mounting of v2 aws creds

---

Dockerfile
Dockerfile.local

BREAKING CHANGE: For anyone mounting halyard configuration, it will now go under /home/spinnaker rather than /root

install(docker): run Halyard as spinnaker user

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ecs/EcsAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ecs/EcsAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ecs/EcsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ecs/EcsCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ecs/EcsEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/ecs/EcsAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/ecs/EcsProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/ecs/EcsAccountValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

PR to add ECS support into Halyard. This also requires [Deck PR 5190](https://github.com/spinnaker/deck/pull/5190)

feat(deploy/ecs): add ecs support to halyard

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java

Since we find a "default" kubeconfig using a "getter", the file was
incorrectly being ignored as "not set" when someone manually removes it
from their halconfig. This can only happen when someone edits their
halconfig by hand.

fix(deploy/kubernetes): fix empty kubeconfig in account definition

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java

If `halyard.halconfig.directory` isn't set, boms live under `halconfigDir/.boms/bom/`. 
If it is set, then boms live under `halconfigDir/bom/`.

fix(localbom): path to local bom should be consistent

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/FileModeUtils.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GitProfileReader.java
halyard-core/src/test/groovy/com/netflix/spinnaker/halyard/core/FileModeUtilsSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RegistryBackedArchiveProfileBuilder.java

Fixes an issue whereby executable files in the packer config directory
would get their execute bit unset when deploying halyard in the local
git mode.

fix(rosco): Preserve file permissions for local git installation

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/GoogleProfileReader.java

Fixes spinnaker/spinnaker#2656

fix(gcs): Retry failed halconfig reads with no authentication

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ProviderUtils.java

Fixed an issue https://github.com/spinnaker/spinnaker/issues/2728
hal deploy apply uses the old style proxy path for kubernetes which was removed in v1.10

Change the kubernetes proxyServiceEndpoint

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/s3/S3EditCommand.java

Solution to "Halyard: s3 --bucket will not accetp s3:// prefix #2408"
fixes #2408
Better solution might be is to find out why the parameter cannot be stored with the s3:// because it should be needed to access the s3 bucket. Possibly the validate function cannot handle the s3:// prefix and the code needed when the bucket is accessed would need updating so this might be the easiest solution.

fix(Halyard): s3 --bucket not accept s3:// prefix

---

README.md

Current scripts' URL can't be installed on Ubuntu 16.04.
[In Spinnaker's documentation](https://www.spinnaker.io/setup/install/halyard/#install-on-ubuntu-14041604), installation on Ubuntu 16.04 is shown, and the URL is also displayed differently.

fix(README): Fix InstallHalyard scripts' URL

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AccountCommandProperties.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/AccountValidator.java

This change also removes the deprecated --requiredGroupMembership flags,
as they are no longer functional.

feat(permissions): Add permissions support for accounts in halyard.

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/versions/BomVersionCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/VersionsService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/VersionsController.java

* When calling `hal version bom`, checks to make sure that the Spinnaker version in the halconfig file is a properly formatted version (string of numbers with 0 or more dots in between, with no dots directly next to each other).
Before:
```
➜  hal version bom        
+ Get current deployment
Success
+ Get Spinnaker version
Success
+ Get current deployment
Success
+ Get Spinnaker version
Success
! ERROR 400 
```
After:
```
➜  ./hal version bom                                                                                             
+ Get current deployment
Success
+ Get Spinnaker version
Success
! ERROR Failed to get BOM versions because Spinnaker version is not
properly formatted in halconfig: version='branch:upstream/master'
```

fix(version/bom): BOM version command displays message if Spinnaker version is not properly formatted.

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth2/EditOAuth2Command.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/OAuth2.java

This PR implements a BYO oauth config mechanism via halyard.
See
https://github.com/spinnaker/halyard/pull/956
https://github.com/spinnaker/spinnaker/issues/2856
https://github.com/spinnaker/spinnaker/issues/2664
Example byo comand
```
./hal config security authn oauth2 edit \
--client-id YYYYYYYYYYYYYYYYY \
--client-secret XXXXXX \
--provider byo \
--access-token-uri https://example.com/login/oauth/access_token \
--user-authorization-uri https://example.com/login/oauth/authorize \
--user-info-uri https://example.com/api/v3/user \
--scope all \
--client-authentication-scheme query \
--user-info-requirements foo=bar \
--user-info-requirements baz=qux \
--user-info-mapping-username username \
--user-info-mapping-first-name firstname \
--user-info-mapping-last-name lastname \ …
```

feat(authn/oauth2): Add commands for byo oauth2

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/AccountValidator.java

Relevant error in clouddriver: 
```
due to violations [ConstraintViolationImpl{interpolatedMessage='must match "^[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*$"', propertyPath=metadata.name, rootBeanClass
=class io.fabric8.kubernetes.api.model.Secret, messageTemplate='{io.fabric8.kubernetes.api.model.Pattern.message}'}]
```
Fixes [#2397](https://github.com/spinnaker/spinnaker/issues/2397)

Updated docker-registry account regex validator

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalGitDeployer.java

Currently haylard will NPE when trying to deploy a localgit deployment of spinnaker that predates kayenta.

fix(deploy): Gracefully handle non-existent services in localgit

---

Dockerfile
Dockerfile.local

Hi - the Dockerfiles seem have a typo in the URL that is used to download the heptio-authenticator-aws binary.
Currently, the URL resolves to
`https://amazon-eks.s3-us-west-2.amazonaws.com/v1.10.3/2018-06-05/bin/linux/amd64/heptio-authenticator-aws`
which returns a "NoSuchKey" error and dumps a non-working file into the Docker image at /usr/local/bin/heptio-authenticator-aws
The correct URL should be
`https://amazon-eks.s3-us-west-2.amazonaws.com/1.10.3/2018-06-05/bin/linux/amd64/heptio-authenticator-aws`
The difference is that the "v" in front of the Kubectl version number must be dropped from this URL.

fix(provider/kubernetes): use the right URL to download heptio

---

install/macos/InstallHalyard.sh

Thanks for your document. I installed halyard in my Mac.
https://www.spinnaker.io/setup/install/halyard/
That original script accepts only java8. So I fixed that and I installed latest halyard in my Mac running Java10. 
If you have no problem about compatibility, could you merge this PR?

fix(install): Fix macosx-install-script's Java version confirmation.

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/CiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/wercker/WerckerAddMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/wercker/WerckerCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/wercker/WerckerCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/wercker/WerckerEditMasterCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/wercker/WerckerMasterCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/wercker/WerckerCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/wercker/WerckerMaster.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java

Added wercker as a ci provider.

feat(ci/wercker): Add wercker ci to halyard

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

Specifying the container name (`orca`) instead of the service
name (`spin-orca`) will enable sizing only for that container
i.e. other containers in the pod will not inherit the sizing.
Fixes spinnaker/spinnaker#3020
Doc update in https://github.com/spinnaker/spinnaker.github.io/pull/927

fix(deploy/kubernetes): Allow container specific custom sizing.

---

install/debian/InstallHalyard.sh
startup/debian/update-halyard

The new install path was not generating the command-completion scripts.
fyi @ttomsu who found this

chore(install): configure command-completion on install

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/oauth2/EditOAuth2Command.java

Fixing a small copy/paste error on setting the username field mapping in oauth. The expected behavior is that it sets the username field as entered in the CLI but due to a bug it instead sets it to the field specified for the last-name (if set).
Here's the command for reference:
https://www.spinnaker.io/reference/halyard/commands/#hal-config-security-authn-oauth2-edit

fix(authn/oauth) copy/paste bug in setting username in oauth user info mapping

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ClouddriverService.java

This is effectively a no-op until spinnaker 1.10
Sample of logs during shutdown:
```
2018-08-17 14:27:00.530  INFO 1 --- [pool-3-thread-1] c.n.s.c.data.task.jedis.JedisTask        : [DEPLOY_KUBERNETES_MANIFEST] - Submitting manifest deployment nginx-deployment2 to kubernetes master...
2018-08-17 14:27:01.571  INFO 1 --- [       Thread-3] ationConfigEmbeddedWebApplicationContext : Closing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@3bc735b3: startup date [Fri Aug 17 14:22:07 GMT 2018]; root of context hierarchy
2018-08-17 14:27:01.606  INFO 1 --- [       Thread-3] o.s.c.support.DefaultLifecycleProcessor  : Stopping beans in phase 2147483647
2018-08-17 14:27:01.608  INFO 1 --- [       Thread-3] o.s.c.support.DefaultLifecycleProcessor  : Stopping …
```

feat(kubernetes): safely shutdown clouddriver as well

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/aws/account/AwsAddCanaryAccountCommand.java

The method `emptyAccount` was returning a `GoogleCanaryAccount` instead of an `AwsCanaryAccount `. Fixed to return the correct implementation.

fix(canary/aws): Use correct impl for aws empty account

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Current halconfig/settings.js has fixed values for aws settings.
It should pick up settings configured by halyard.
This works with https://github.com/spinnaker/deck/pull/5681 .
Ref: https://github.com/spinnaker/spinnaker/issues/3271

feat(deploy): Add default AWS settings to deck

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/LdapRoleProvider.java

Fixes https://github.com/spinnaker/spinnaker/issues/3154

fix(authz/ldap): Fix incorrect node name for ldap role provider.

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AccountCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/openstack/OpenstackEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/openstack/OpenstackAccount.java

The `credentials.challengeDestructiveActionsEnvironments` setting in
clouddriver controls a few features in deck. This setting is based off
the configured environment for an account. Adding environment to the
add and edit account commands allows use of halyard to take advantage of
those deck features.
Moving the environment flag up from the Openstack subclasses makes it
available to all account types.

fix(cli/accounts): Allows specifying environments for accounts

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

the regex used in `replaceAll` in `makeValidLabel` was incorrect not
replacing chararacters. the intent was to remove all characters that are
not `A-Za-z0-9-_.` but using a leading and trailing `/` broke it. by
removing the `/`, we get the desired effect.
@lwander PTAL :)

fix(deploy): fix regex for illegal char replace

---

install/debian/InstallHalyard.sh
install/macos/InstallHalyard.sh
startup/debian/update-halyard
startup/macos/update-halyard

On Ubuntu 18.04 on GCE, gcloud is installed by snap in /snap/bin. There is an entry to add /snap/bin to the path in /etc/profile.d but this only runs for login shells, so if halyard runs in a non-login shell it is unable to find gcloud. Rather than address the specific case, we should start the halyard daemon in a login shell.

fix(install): Halyard startup should use a login shell

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/api/SpringSslEditCommand.java

The --client-auth parameter is incorrectly marked as a password, forcing the user to enter it at a prompt.

fix(cli): Allow --client-auth to be entered on the command line

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/git/LocalGitDeckService.java

Our webpack config is expecting the deck host as an environment variable.

fix(localgit): Pass deck host as environment variable

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/LdapRoleProviderValidator.java

This PR is to allow anonymous LDAP search (managerDn and manager password both empty). Fiat supports it but Halyard doesn't allow that configuration.

fix(authz): allow anonymous LDAP bind

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

The gate health check is currently broken when SSL is enabled. The request is to the localhost domain and does not pass in any additional trusted CA's; the request will thus fail unless gate presents a certificate for localhost issued by a root CA (which I believe will never be validly issued). As the request is within the pod to localhost, validating the certificate does not have high value, so just pass a flag to wget to skip certificate validation.

fix(kubernetes/health): Fix Gate health check with SSL enabled

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

Adds the passwordCommand option to halyard, https://github.com/spinnaker/clouddriver/pull/2837

feat(provider/docker): Configure passwordCommand for docker registry

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ProviderUtils.java

Making a PR for discussion on Monday.
Issue here: https://github.com/spinnaker/spinnaker/issues/3435#issuecomment-429375735
This user of the spinnaker helm chart is attempting to deploy a v1 account but seeing an error because the kubecfg is null. It looks like the kubecfg parser can deal with this by using the provided service account instead but needs to be instructed to do so.
I'm having some trouble compiling this to test against.  Getting the following gradle error:
```
(master) λ ./gradlew clean
Inferred project: halyard, version: 0.37.0-SNAPSHOT
FAILURE: Build failed with an exception.
* Where:
Build file '/Users/sbws/dev/spinnaker/halyard/build.gradle' line: 36
* What went wrong:
A problem occurred evaluating root project 'halyard'.
> Failed to apply plugin [class …
```

fix(provider/kubernetes): v1 - pass account service account to kubecfg parser

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/oracle/OracleAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/oracle/OracleEditArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/oracle/OracleEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/oracle/OracleEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/oracle/OracleArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/OraclePersistentStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/oracle/OracleAccount.java

Allow Allow oracle provider/bakery/artifact/storage to use private key file with passphrase.
Related PRs are https://github.com/spinnaker/clouddriver/pull/3043, https://github.com/spinnaker/rosco/pull/294, and https://github.com/spinnaker/front50/pull/379.

fix(provider/oracle): add private key passphrase

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

The previous patch didn't get the bug, it is on an empty list, not an empty name.  This checks both.
https://github.com/spinnaker/spinnaker/issues/3280

fix(deploy): fix deploy w/o aws region specified

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerMonitoringDaemonService.java

Halyard will look for ~/.hal/default/profiles/monitoring-daemon/filters/default.yml, and if it exists will mount it stage it. 
This PR will be followed by lwander mapping that staged copy onto all monitoring-daemons.

feat(halyard): Halyard configures filters on monitoring-daemons.

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/SidecarConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConfigSource.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/container.yml

Sample config for a clouddriver sidecar:
```yaml
...
spin-clouddriver:
- name: creds
env:
one: two
command:
- custom
args:
- build
- credentials
mountPath: /home/spinnaker/.aws
dockerImage: busybox
- name: dns
dockerImage: busybox
...
```
@ethanfrogers fyi

feat(deploy): specify custom sidecars for k8s v2

---

halyard-backup/src/main/java/com/netflix/spinnaker/halyard/backup/services/v1/BackupService.java

I was getting errors like
```
java.lang.RuntimeException: file name '....' is too long ( > 100 bytes)
```
Looking at the docs, http://commons.apache.org/proper/commons-compress/tar.html#Long_File_Names 
>LONGFILE_POSIX: use a PAX extended header as defined by POSIX 1003.1. Most modern tar implementations are able to extract such archives. since Commons Compress 1.4
`hal backup restore` works fine with long filenames without a problem.

feat(backup): allow long filenames

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3AddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/s3/S3EditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/s3/S3ArtifactAccount.java

adds options for setting the awsAccessKeyId and awsSecretAccessKey
Depends on spinnaker/clouddriver#3083

feat(artifacts/s3): add aws keypair support

---

.gitignore
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Notification.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ValidForSpinnakerVersion.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/FieldValidator.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java

Twin of https://github.com/spinnaker/deck/pull/5894
Appengine Container URL deploys will now always be available in deck.

feat(halyard): Add support for deprecating flags

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml

Containers are specified in exactly the k8s container model:
```yaml
...
initContainers:
spin-clouddriver:
- name: init-me
image: busybox
volumeMounts:
- mountPath: /config
name: config
```
https://github.com/spinnaker/halyard/pull/1080

feat(deploy/kubernetes): support custom init containers

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml

```yaml
hostAliases:
spin-clouddriver:
- ip: "127.0.0.1"
hostnames:
- "local.local"
```
https://github.com/spinnaker/halyard/pull/1080

feat(deploy/kubernetes): host alias support

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/SidecarConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConfigSource.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/configMapVolume.yml

```yaml
...
sidecars:  
spin-clouddriver:
- name: creds
env:
one: two
command:
- custom
args:
- build
- credentials
mountPath: /home/spinnaker/.aws
dockerImage: busybox
configMapVolumeMounts:
- configMapName: demo
mountPath: /path/to/config
```
#1080

feat(deploy/kubernetes): custom sidecars configmaps

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

With several kube clusters configured, clouddriver can take several
extra minutes to start up as it does the permissions checks. Multiply
that by several instances of clouddriver and rollouts start to get
unwieldy. This allows the startup permission scan to be disabled and
save lots of time.

feat(provider/kubernetes) support for setting checkPermissionsOnStartup

---

Dockerfile

Per discussion in spinnaker/spinnaker#2394, adding awscli to container
such that the features added in spinnaker/spinnaker#2941 to enable
an external passwordCommand for a docker registry can be utilized by
AWS users wishing to add their ECR-based docker registries.
Signed-off-by: Joe Hohertz <joe@viafoura.com>

Add aws cli to container build

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml

Ran into this recently when trying to deploy to an EKS cluster using manifest-based deployments.

fix(kubernetes/v2): Adds imagePullSecrets to podSpec.yml for V2 Kubernetes deployments

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/ArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/helm/HelmAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/helm/HelmArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/helm/HelmArtifactProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/helm/HelmEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/bitbucket/BitbucketArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gcs/GcsArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gitlab/GitlabArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/helm/HelmArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/helm/HelmArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/http/HttpArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/oracle/OracleArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/ArtifactProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ArtifactProviderService.java

Issue: spinnaker/spinnaker#3284

feat(artifacts): Add support for helm/chart artifacts

---

startup/debian/hal
startup/macos/hal

The startup script is breaking apart arguments with spaces in them. Spaces in arguments become important when configuring docker-registry with a `--password-command`. The lack of argument escaping was causing errors as actual hal tried to parse the password-command arguments as its own.
Brief explanation of the specific shell syntax: https://stackoverflow.com/a/905910

fix(run): Pass argument escaping through startup script

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

add custom `ConfigMap` or `Secret` volume mounts at the service level.
This allows you to mount extra config or secrets as needed.

feat(deploy/kubernetes): custom volume mnt per svc

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Webhook.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/webook/WebhookTrust.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java

This PR add the ability for Halyard to parse the webhook.trust configuration paramters and write them
to orca.yml (including the ability to back up the local trust store file).
Updates to add 'hal' commands to configure this will be in a later PR.

feat(webhooks): Allow config of custom trust store

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentEnvironment.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java

Config will now allow nodeSelectors to be added to the deployed spinnaker nodes. (Tested in kubernetes v1)
```
...
nodeSelectors:
service_type: api
```

Add nodeSelector in .hal/config file kubernetes v1

---

halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/AccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ArtifactAccountController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ArtifactProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/BakeryController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/CanaryController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/CiController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ClusterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentEnvironmentController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/FeaturesController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/HaServiceController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MasterController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/MetricStoresController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/NotificationController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PersistentStorageController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ProviderController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PubsubController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SecurityController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/SubscriptionController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/WebhookController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/models/v1/DefaultValidationSettings.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/models/v1/ValidationSettings.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/models/v1/ValidationSettingsHandler.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/util/v1/GenericGetRequest.java

There's a lot of duplicated code in the halyard controllers; make it easier to configure new endpoints by factoring duplicated code into a `GenericGetRequest`.  The net number of lines removed is not huge (net negative of ~10 lines per controller) but this should make it conceptually a lot easier to write a new controller.  I plan to do a similar thing for update requests where there is actually a lot more duplicated code.  The goal is to lower the barrier for adding config parameters to halyard.

 refactor(controller): Refactor common logic in controller GET handling

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfileFactory.java

- Fixes bug where Restrict Execution During Time Window stages always calculate whether the current time is within range using PST rather than a user's configured timezone

fix(config/orca): set global.spinnaker.timezone for orca

---

Dockerfile
Dockerfile.local

- Use latest version of the aws authenticator
- Use aws-iam-authenticator instead of deprecated heptio-authenticator-aws
See - https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html
Signed-off-by: S.Cavallo <smcavallo@hotmail.com>

fix(eks): Use latest aws authenticator 

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml

At least in OpenShift, we need to run certain Services under a
serviceAccountName, in order to be able to run containers under
anyuid.

Allow specifying of serviceAccountName

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/ArtifactTemplate.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Artifacts.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/EchoProfileFactory.java

Add the ability for Halyard to parse the configuration of artifact templates and write them to echo.yml; the commands to write the config using hal commands will be in a separate change.

feat(artifacts): Allow config of artifact templates

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/SidecarConfig.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceTest.groovy

Allows deployment of (for instance) `cloudsql-proxy` sidecars, which are useful when dealing with Google CloudSQL (when you're running `orca-sql` for instance)
Tested & working sample config for a `spin-orca` sidecar:
```
sidecars:
spin-orca:
- name: cloudsql-proxy
port: 3306
dockerImage: gcr.io/cloudsql-docker/gce-proxy:1.13
command:
- "'/cloud_sql_proxy'"
- "'--dir=/cloudsql'"
- "'-instances=project-name:gcp-region:cloudsql-instance=tcp:3306'"
- "'-credential_file=/secrets/cloudsql/credentials-cloudsql-instance.json'"
mountPath: /cloudsql
secretVolumeMounts:
- mountPath: /secrets/cloudsql
secretName: cloudsql-instance-credentials
- mountPath: /var/run/secrets/kubernetes.io/serviceaccount
secretName: default-token-8pndx
```
#1080

feat(deploy/kubernetes): custom sidecars secret volume mounts

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/SpinnakerService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml

Background
When using HA mode the sidecar support is hard to configure due to the differing service names. Since the configuration is done per deployment this makes managing multiple sidecars unwieldy. 
Change
Add a check for canonical name of the base service if a service specific config is not supplied.
The configuration works as follows:
Check for Service Name configs (spin-clouddriver) 
-> if not set check the canonical name (clouddriver)
-> done 
Test
Compiled and ran tests, there are no tests for this particular module, cut a custom build and applied changes via service name and canonical name

feat(deploy/kubernetes) - add ability for sidecars to be applied by canonical name

---

.dockerignore
Dockerfile

Removed depricated mantainer instruction, replaced with `LABEL maintainer=`
Changed to multi-stage dockerfile as the rm -rf workdir doesn’t delete the workdir from the prior layer. This cuts down the final docker image size by 700Mb.
https://docs.docker.com/develop/develop-images/multistage-build/#use-multi-stage-builds

chore(dockerfile): decreased docker image size

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/service.yml

kubernetes:
serviceType: NodePort
nodePort: 30085

feat(deploy/kubernetes): add serviceType to kubernetes service settings

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/aws/AwsCanaryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/google/GoogleCanaryAccount.java

This ensures that the generated kayenta.yaml keeps the same order for
supported types.

fix(kayenta/setorder): Make Kayenta canary account supported types ordered.

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

Clouddriver was updated to require an okhttp client to be passed to DockerRegistryNamedAccountCredentials, which broke halyard when we bumped the dependencies. Pass in the default client.

fix(docker): Fix docker validation

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/SpinnakerRuntimeSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpinnakerProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ServiceSettings.java

This prevents unnecessary churn in each Kubernetes Deployment object when Spinnaker is deployed. The root cause was:
1. Things like `targetSize` (a field inside `ServiceSettings`) was changed... 
1. which caused the file hash of `spinnaker.yml` to change...
1. which caused the Deployment object to be updated...
1. which invoked a Rollout by Kuberenetes...
1. which rebooted every service.

fix(deployment): Only include baseUrl and enabled for each service in spinnaker.yml

---

startup/debian/update-halyard

Not using `hal shutdown`, since old version may not support the command.

fix(update-halyard): restart daemon on upgrade

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureProvider.java

Currently halyard doesn't have command to configure regions for Azure provider.
Add regions property in hal-config and default value "eastus","westus"
Command | result
-- | --
Hal config provider azure account add/edit --help | --regions       The Azure regions this Spinnaker   account will manage.
hal config provider azure account add/edit   my-azure-account --regions a,b | regions:           - a           - b
Hal config provider azure account add (without setting regions) | regions:           - westus           - eastus

feat(provider/azure): Add regions support for Azure provider

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/RoscoProfileFactory.java

The rosco profile factory is currently writing out the account configuration before local files are backed up to the halyard staging directory. This means the rosco profile contains a reference to the key at the raw file location, which may not be readable by Spinnaker.
Fixes a bug introduced in #1183, which was caught by our integration tests.

fix(rosco): Fix backup of service account key

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/secrets/SecretSessionManager.java

Part of secrets management: spinnaker/spinnaker#3649

fix(secrets): decryptAsFile returns the string passed in if unencrypted

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/saml/EditSamlCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Saml.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SamlConfig.java

Fixes https://github.com/spinnaker/spinnaker/issues/3987
Expose the configuration for userAttributeMapping when using SAML as Identity provider.
New parameters added for saml
```
./hal config security authn saml edit --help
...
--user-attribute-mapping-first-name
The first name field returned from your SAML provider.
--user-attribute-mapping-last-name
The last name field returned from your SAML provider.
--user-attribute-mapping-roles
The roles field returned from your SAML provider.
--user-attribute-mapping-roles-delimiter
The roles delimiter field returned from your SAML provider.
--user-attribute-mapping-username
The username field returned from your SAML provider.
```
Using the new `userAttributeMapping` parameters:
```
./hal config security authn saml edit …
```

feat(authn/saml): Add userAttributeMapping to saml configuration

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gcs/GcsArtifactAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/google/GoogleCanaryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/GcsPersistentStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/GoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/pubsub/google/GooglePublisher.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/pubsub/google/GoogleSubscription.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/canary/google/GoogleCanaryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/GoogleAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/google/GoogleProviderValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleProviderUtils.java

The original change was adding support for storing credentials in an encrypted s3 bucket instead of a plain text file. This is part of the secrets management project here: https://github.com/spinnaker/spinnaker/issues/3649
The problem:
We're seeing an NPE from `GoogleAccount.getNamedAccountCredentials` because we're trying to autowire the `SecretSessionManager` in a class that's not being managed by Spring. The NPE occurs when we try to call `secretSessionManager.validatingFileDecrypt(p, getJsonPath())`.
The fix:
Removing the autowired `SecretSessionManager` in both `GoogleAccount` and `GoogleCanaryAccount` and instead passing it in from the upstream callers where supported. Namely these upstream validators: `GoogleAccountValidator`, `GoogleProviderValidator`, …

fix(secrets): fix gce credential loading

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/KubectlDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1ProviderUtils.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubectlServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Executor.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java

Part of secrets management project: [spinnaker/spinnaker#3649](https://github.com/spinnaker/spinnaker/issues/3649)
So far, we've been adding an autowired SecretSessionManager to deal with decryption, but kube configs are handled in static methods in KubernetesV2Utils. Since you can't static autowire, it seems the cleanest solution is to make those methods non-static and make adjustments in the couple classes that call them.
We also have to remove the static autowire in Kubernetesv1Utils, so secrets in v1 kubernetes is unsupported for now.

feat(secrets): add support for decrypting kube configs

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/DeploymentEnvironmentCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/AbstractComponentSizingUpdateCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/ComponentSizingCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/ComponentSizingDeleteCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/ComponentSizingEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/NamedComponentSizingCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/CustomSizing.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/DeploymentEnvironmentValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/HaClouddriverValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/HaEchoValidator.java

fixes https://github.com/spinnaker/spinnaker/issues/3981
```
spinnaker@halyard:$ hal config deploy component-sizing orca edit --replicas 3
+ Get current deployment
Success
+ Get the deployment environment
Success
+ Edit the deployment environment
Success
+ Successfully edited component sizing for service orca.
spinnaker@halyard:$ hal config deploy component-sizing orca
+ Get current deployment
Success
+ Get the deployment environment
Success
+ Successfully got component sizing for service orca.
{replicas=3}
```
`$ cat ~/.hal/config`
```yaml
currentDeployment: default
deploymentConfigurations:
size: SMALL
type: Distributed
....
customSizing:
spin-orca:
replicas: 3
```
```sh
$HAL_COMMAND config deploy component-sizing clouddriver edit --pod-requests-cpu 250m …
```

feat(deployments): add command for component sizing on kubernetes distributed deployments

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/ComponentSizingDeleteCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/ComponentSizingEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/deploy/sizing/NamedComponentSizingCommand.java

The prior commit implemented getShortDescription for new commands, but not either getLongDescription or getDescription. As a quick fix, just rename the getShortDescription to getDescription which fixes docs generation.

fix(deployments): Fix docs generation

---

halyard-cli/halyard-cli.gradle

The Halyard docs are currently generated via a makefile. Move this to gradle so that it can be incorporated into the build process rather than a separate shell command.
In particular, the check task should fail if the docs do not generate properly or if the docs committed to git do not match what are generated from source. This will cause our Travis build to fail and block merging when a PR either forgets to update the docs or breaks doc generation.

feat(core): Use gradle to generate docs

---

install/debian/InstallHalyard.sh

I ran into this installing Halyard from a debian 9 dockerfile.
All of the other `apt install` commands run non-interactively other than installing Java. Maybe adding ca-certificates is something you want someone to acknowledge, but if that's the case, then when someone does
```
InstallHalyard.sh -y
```
*everything* should be non-interactive.
I also had to have my dockerfile manually add `stretch-backports` to `/etc/apt/sources.list.d/stretch-backports.list`
Edit: fixes https://github.com/spinnaker/spinnaker/issues/4045

fix debian noninteractive install

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineAccount.java

Allows a user to configure Spinnaker to hit the AppEngine Admin API less often, thereby reducing the risk of hitting quotas.

feat(appengine): add flag to configure caching agent interval

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java

There's been some discussion in Slack that the `liveManifestCalls` feature works wonderfully, but should not have to be manually added to one's halconfig.

feat(kubernetes): add live-manifest-calls flag to cli

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSecurityContext.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/podSpec.yml

This is for being able to specify the `securityContext` under which spinnaker's pods will run. Example `service-settings/clouddriver.yml`:
```
kubernetes:
securityContext:
runAsUser: 99
fsGroup: 99
```
Results in:
```
bash-4.4$ whoami
whoami: unknown uid 99
bash-4.4$
bash-4.4$ ls -la /opt/spinnaker/
total 0
drwxr-xr-x    3 root     root            20 Mar 19 17:21 .
drwxr-xr-x    1 root     root            23 Mar 19 17:21 ..
drwxrwsrwt    3 root     99             120 Mar 19 17:20 config
bash-4.4$
```

feat(provider/kubernetes): Pods security context in service-settings

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/ResourceBuilder.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/container.yml
halyard-deploy/src/main/resources/kubernetes/manifests/tcpSocketLivenessProbe.yml

Per discussion on https://github.com/spinnaker/spinnaker/issues/4023, reuses `readinessProbe` as a `livenessProbe` so that containers that fail health checks are not only removed from the load balancer, but also restarted automatically.

feat(kubernetes): add livenessProbe

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/ResourceBuilder.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/container.yml
halyard-deploy/src/main/resources/kubernetes/manifests/tcpSocketLivenessProbe.yml

Reverts spinnaker/halyard#1253
Adding a `livenessProbe` with no configured `initialDelaySeconds` causes services with long startup times to crash and restart indefinitely. However, we are hesitant to introduce another user-configured value that can only be discovered after an initial failed deployment experience, with no obvious default. Reverting this change until we land on the best way to configure a `livenessProbe` that will work for most users out of the box.

Revert "feat(kubernetes): add livenessProbe"

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/SecretFile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/secrets/DecryptingObjectMapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SamlConfig.java

Normally, secret annotations are placed on secret fields in the config classes so that the `DecryptingObjectMapper` knows which fields to decrypt when serializing. In the case of `Saml`, the `GateProfileFactory` creates a new `SamlConfig` object instead of passing the `Saml` object itself to the `DecryptingObjectMapper`. Therefore, the `SamlConfig` class needs annotations on secret fields in order to decrypt when printing the service profiles.

fix(secrets): fix saml secret decryption

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/azure/AzureEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureAccount.java

Provide users with the option of using SSH public key or password to provision linux vm during hal setup. The backend function is in the clouddriver [PR](https://github.com/spinnaker/clouddriver/pull/3468)

feat(provider/azure): Add SSH public key support to provision linux vm

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/secrets/v1/SecretSessionManager.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/secrets/DecryptingObjectMapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Profile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Utils.java

Part of spinnaker/spinnaker#3649
Some secrets, such java keystore files, will be binary files, so we want to be able to cache and pass to kubernetes as byte arrays instead of strings. This adds that functionality.
@dibyom

feat(secrets): add decryptAsBytes to enable decryption of binary files

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

The idea here is to allow `hal config feature edit` to accept `--gremlin` as an argument.
Then, that setting will appear as `features.gremlin` to `deck`, `orca`, and `gate`.

feat(gremlin): Allow Gremlin to get configured via Halyard

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/metricStores/datadog/DatadogStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/metricStores/stackdriver/StackdriverStore.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Secret.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/SecretFile.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/secrets/DecryptingObjectMapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileFactory.java

Monitoring secrets (Datadog, Stackdriver) won't have Kork decryption and need to be mounted decrypted. This is done by adding a `alwaysDecrypt` on `@Secret` and `@SecretFile` and simplifying the object mapper annotation check.

fix(secrets): Always decrypt monitoring secrets

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Executor.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

This PR fixes the issue of deploying Spinnaker in Kubernetes when the halconfig is quite big (~35 accounts and more):
https://community.spinnaker.io/t/halyard-with-v2-metadata-annotations-too-long/894
Unlikely, `kubectl apply`, the `kubectl replace --force` command does not preserves
current data to the annotation. That allows to work around the issue when the halyard config is quite big and could not fit into the annotation.

fix(halyard): Use "kubectl replace --force" for Kubernetes Secret creation

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/secrets/DecryptingObjectMapper.java

The saml keystore requires a "file:" prefix in the `gate.yml`, which is currently added in the `secretFileSerializer`.  The bug: when secret decryption is supported in the services AND the keystore file is not an encrypted secret, the code skips the custom secretFileSerializer, which means "file:" doesn't get prepended to the path.  This fixes the logic so that an encrypted secret that should stay encrypted doesn't get the prefix, but all other cases do.

fix(secrets): fix file prefix for saml keystore

---

install/debian/InstallHalyard.sh

The call to 'which systemd-users' returns an exit status >0 when it fails.  As we're running under 'set -e' this causes the script to immediately exit in failure.
Bash does not exit in failure when the command that produces an exit value >0 is part of an if condition.  That's actually what we want here; just run the command directly in the 'if'.

fix(install): Fix installation on debian-based systems

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractGetAccountCommand.java

This pull request fixes an issue that `hal config provider * account get` doesn't use `--no-validate` parameter.
For example, the commands document says that `hal config provider docker-registry account get` supports the `--no-validate` option: 
https://www.spinnaker.io/reference/halyard/commands/#hal-config-provider-docker-registry-account-get
But actually it doesn't work properly because the `validate` option is hard-coded in the code.
( Currently always skip validation )
This pull request fixes the issue.
This issue was introduced in https://github.com/spinnaker/halyard/commit/668ad922ac854a1caede3d49fdfe45e39fa114be#diff-b7acb0a85fc298aec1a196698cbc8fdeR45

fix(cli): Use "--no-validate" parameter on "hal config provider * account get"

---

halyard-web/halyard-web.gradle

spring.config.node is not the correct property to be setting, therefore local running halyard daemons, via gradlew don't pick up the halyard-local.yml configuration.

fix(local halyard): Correctly set spring config location.

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/master/AbstractListMastersCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/concourse/ConcourseCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/jenkins/JenkinsCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/wercker/WerckerCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Ci.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/CiService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/ConcourseService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/JenkinsService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/TravisService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/WerckerService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/CiController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/ConcourseController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/JenkinsController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/TravisController.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/WerckerController.java

* refactor(ci): Remove unused code 
Some of the CI methods are unused, as we don't actually have any halyard commands or endpoints to list all CI accounts regardless of type.
* style(ci): Fix indentation 
Some of the files I added in the last PR ended up with 4-space indents; fix this as a separate commit to reduce the diff on later commits.
* refactor(ci): Move more things to base classes 
We can make the classes I added in the last PR a bit simpler by pushing some things to the base class.
* refactor(ci): Rename interface method getAccounts 
We'll allow implementations of CIAccount to call their accounts field whatever they want (masters, accounts, etc.) but will have the top-level interface expose getAccounts().
Push the 'masters' field down into the existing classes; we can't rename …

refactor(ci): Rename interface method getAccounts

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/gcb/GoogleCloudBuild.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/gcb/GoogleCloudBuildAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/GoogleCloudBuildService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/EchoProfileFactory.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/GoogleCloudBuildController.java

This PR does not yet add commands for manipulating the config; these will be in the next PR.
* feat(gcb): Add GCB configuration to Halyard 
The configuration should be added to both igor and echo. This commit only adds functionality for parsing these fields in the halconfig and generating the correct entries in the igor/echo config. A future commit will add 'hal' commands to edit this block in the halconfig.
* feat(gcb): Add service and controller for GCB config

feat(gcb): Add GCB configuration to Halyard

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/master/AbstractListMastersCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/CiType.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/concourse/ConcourseCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/gcb/GoogleCloudBuild.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/jenkins/JenkinsCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/travis/TravisCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/wercker/WerckerCi.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Ci.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/CiService.java

* fix(ci): Fix error casting CI class from daemon 
It turns out that removing the objectMapper from the halyard-cli commands broke deserializing the result from the daemon. We'll need to continue to conver the result to the expected class.
Instead of adding back reflection, make a small enum that keeps track of the classes relevant for each CI system, and call that enum to do the mapping.
* fix(ci): Rename getAccounts to listAccounts 
The interface method getAccounts starts with 'get' so the JSON serializer is assuming that it is the accessor for a property; this means that requests for jenkins accounts are returning accounts under both 'masters' and 'accounts' because both getMasters and getAccounts are defined.
We could add @JsonIgnore to the getAccounts interface method, but we don't …

fix(ci): Fix two bugs from refactor of halyard CI commands

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/CiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildListAccountsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GooglecloudBuildDeleteAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/master/AbstractHasAccountCommand.java

Prior commits added support for including these in the hal config and for generating service configs including gcb accounts. This commit just adds the hal commands to edit these accounts.

feat(gcb): Add hal commands for manipulating gcb accounts

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/ldap/EditLdapCommand.java

Fixes spinnaker/spinnaker#4393
The non-ASCII quotes seem to be causing issues for some users; theoretically they should work but rather than worry about debugging encoding issues, just replace them.

fix(halyard): Replace non-ASCII quotes

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/persistentStorage/s3/S3EditCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/S3PersistentStore.java

There are two styles to access s3 bucket: `virtual hosted-style` and `path-style`. Users can config which one they want to use.
I make this option default false which means using `virtual hosted-style` in considering `path-style` access is already deprecated by AWS([Amazon S3 Path Deprecation Plan – The Rest of the Story](https://aws.amazon.com/cn/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/)).

feat(s3): Add --path-style-access option to config s3 bucket access style (#4400)

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianRedisService.java

When installing redis on ubuntu 16.04, it is not enabled by default (as opposed to 14.04 and 18.04 where it is). This breaks our integration tests, and also likely confuses users who need to manually start it even after deploying with halyard. To fix this, ensure the service is started after installing.  (systemctl won't
exist on 14.04, so guard that statement with a || true)

fix(redis): Ensure redis is started

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/appengine/AppengineEditCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/appengine/AppengineProvider.java

Clouddriver searches the the PATH for the gcloud executible; in some cases it is easier to provide a direct path to the executable than to fully control the environment of clouddriver.
(One example is running it on Ubuntu 18.04 on GCE; gcloud is installed in /snap/bin, which is added to the path for login shells but is not in the path for systemd.)
The clouddriver change will just fall back to searching the path if this parameter is unset.

fix(appengine): Allow path to gcloud to be configured

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/deployment.yml
halyard-deploy/src/main/resources/kubernetes/manifests/service.yml

This allows adding customized labels to the pods and services created by Halyard for Spinnaker services.

feat(kubernetes): Allow adding custom pod and service labels

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/GateProfileFactory.java

Halyard now adds the integrations block to the gate config, but 1.13.x versions of Spinnaker already have it defined in the hal config, which leads to duplicate 'integrations' blocks, breaking gate startup.
Unfortunately there's not currently a great way of addressing this; as a workaround just remove that block on-the-fly if we encounter it.

fix(integrations): Fix duplicate config block

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java

We removed support for OpenStack, but this is causing Halyard to fail validation if there is an openstack block in the config. This is particularly bad as Halyard adds an empty block by default for each provider, so even users who have never used openstack are seeing validation failures after the release of 1.20.0.
Explicitly ignore the "openstack" field on deserialization so we don't cause validation errors.

fix(*): Don't fail validation if openstack is present

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java

Fixes spinnaker/spinnaker#4399
When deploying to Kubernetes, supporting files (such as credentials) are added as files in a Kubernetes secret, which does not allow special characters in file names. Strip special characters out of the file names before we generate the staged file for backing up.

fix(deploy): Handle files with special characters

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildEditAccountCommand.java

The GCB command parameters are camel case, which is inconsistent with all other halyard commands. Fix this now before the feature is live in Spinnaker and users are depending on these.

fix(gcb): Fix gcb command parameters

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

* `--api` -> `--api-host`
* `--appsManagerUri` -> `--apps-manager-uri`
* `--metricsUri` -> `--metrics-uri`
Still supports the original parameter format for backward compatibility.

refactor(cf): Improved consistency of `hal config provider cloudfoundry add/edit` parameters

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

This exposes `cacheThreads` in the CLI. Also added `allNamespaces` which was not implemented (I took it as clear the namespaces currently whitelisted).

feat(kubernetes): Support cacheThreads and implement allNamespaces

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/LdapConfig.java

Is possible to set managerDn and managerPassword for auth using halyard-cli but the values are not reflected in gate.yml

fix(ldap): add managerDn and managerPassword to gate's auth configuration

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryEditAccountCommand.java

The api-host, user and password fields didn't need to be mandatory.

fix(cf): All CF account fields now optional on edit

---

halyard-web/halyard-web.gradle

The boot2 upgrade removed halyard-cli as a dependency of halyard-web. This was reasonable to do, as halyard-web does not directly depend on any functionality of halyard-cli. Unfortunately, the halyard install
process does not separately install halyard-cli; it only installs halyard-web into /opt/halyard but the CLI nonetheless expects to find its jar file there.
This means that currently the halyard-cli won't run when installed using the Halyard installer. While there's almost certainly a better way of implementing this, just re-add the dependency for now to unbreak halyard.

fix(core): Fix halyard cli

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Node.java

Fixes spinnaker/spinnaker#4499.
If a user's hal config has a file that has no parent directory (which is likely a misconfiguration) we throw an NPE instead of the usual user-facing error that the file doesn't exist.  Protect against the NPE so the usual (and more useful) error message shows up.

fix(deploy): Fix NPE for incorrect file name

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/httpReadinessProbe.yml

Setting _kubernetes.useExecHealthCheck: false_ as a custom service setting for gate configures the Kubernetes readiness probe to use the built-in httpGet functionality instead of using the external wget command. We made this change to resolve the issue that we reported in #4479. However, we then found that the HTTPS scheme is not specified when the endpoints use TLS thereby resulting in failed readiness probes. This pull request adds the missing support for the HTTPS scheme.

fix(kubernetes): Added the missing support for the HTTPS scheme to Kubernetes httpGet readiness probe

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java

Recent changes broke `shutdown`
```
$ ./hal shutdown
! ERROR 400
? Try the command again with the --debug flag.
```
```<--- HTTP 400 http://localhost:8064/shutdown (317ms)
X-Content-Type-Options: nosniff
X-XSS-Protection: 1; mode=block
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
Pragma: no-cache
Expires: 0
X-Frame-Options: DENY
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Date: Wed, 19 Jun 2019 18:19:18 GMT
Connection: close
OkHttp-Sent-Millis: 1560968358743
OkHttp-Received-Millis: 1560968358755
{
"timestamp" : "2019-06-19T18:19:18.751+0000",
"status" : 400,
"error" : "Bad Request",
"message" : "JSON parse error: Cannot construct instance of `java.util.LinkedHashMap` (although at least one Creator exists): no String-argument constructor/factory …
```

fix(shutdown): Replace String with StringBodyRequest

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/AccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/dockerRegistry/DockerRegistryAccountValidator.java

The regex used to validate the account name was applied to accounts for all providers but this is only a requirement for the docker registry provider accounts.
Every account type other than docker registry (and only when used by a kubeV1 account) have no specific format requirements in clouddriver for the account name, yet the regex was applied to every account type. This was limiting for users naming account with schemes that includes various characters.

fix(config/validation): Moved strict account name validation to docker only

---

halyard-web/halyard-web.gradle
halyard-web/src/main/java/com/netflix/spinnaker/halyard/Main.java

The resolvedEnv endpoint was inadvertently disabled as part of the boot2 upgrade because it moved to a package that's not in the classpath scan.  Re-enable it.

fix(core): Re-enable resolvedEnv endpoint

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/ApachePortsProfileFactory.java

The Deck pod was failing to start after a recent apache2 version bump in the image(2.4.25 to 2.4.38): `(98)Address already in use: AH00072: make_sock: could not bind to address 0.0.0.0:9000`
Happening only when SSL was enabled.
Starting from apache2 2.4.28, having multiple `Listen` directive listening to the same socket is forbidden:
- https://svn.apache.org/repos/asf/httpd/httpd/branches/2.4.x/CHANGES
- https://httpd.apache.org/docs/2.4/mod/mpm_common.html#listen
In this case, no need for multiple Listen directive as we always listen on the same one socket whether SSL is enabled or not.

fix(deploy/deck): Port conflict in ports.conf

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/StrictObjectMapper.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/NodeSpec.groovy
halyard-config/src/test/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccountTest.java

The old version of Lombok used in Halyard <=1.21 didn't copy
@JsonProperty annotations to the generated methods. This means Jackson
was seeing the field as 'oAuthScopes' and the getter/setter as a
separate 'oauthScopes' property. The same data would be written to both
properties, and during parsing whichever came last in the file would be
persisted into the object.
With new versions of Lombok (>=1.18.8), the @JsonProperty annotation is
copied to the bean methods, so the 'oauthScopes' property disappears and
Jackson can no longer parse those old files.
This commit adds some methods to support parsing the files generated by
previous versions of Halyard, but will no longer write out the
incorrect duplicate data.

fix(config): parse 'oauthScopes' stanzas that were incorrectly written

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/google/GoogleCanaryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Validator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/util/ValidatingFileReader.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/canary/CanaryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/canary/google/GoogleCanaryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/canary/prometheus/PrometheusCanaryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/SamlValidator.java

Fixes https://github.com/spinnaker/spinnaker/issues/4665
Also further consolidates all external file access into `ValidatingFileReader`.

fix(core): Fix reading of external files as binary instead of text

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/secrets/BindingsSecretDecrypter.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/AwsCredentialsProfileFactoryBuilder.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/TemplateBackedProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/consul/ConsulClientProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/ApachePassphraseProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/ApachePortsProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/ApacheSpinnakerProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckDockerProfileFactory.java

Deck doesn't have secret decryption implemented, but we still want to allow users to use the secret format for SSL certs, etc, in their hal config. The change here makes sure those secrets are decrypted before building the deck profile.
@ezimanyi PTAL whenever you have a chance? (or let me know if I should tag someone else?)
Thanks!

feat(secret): decrypt secrets before sending to deck

---

build.gradle

Spinnakerbot now uses gradle.properties to autobump the kork version ([example](https://github.com/spinnaker/halyard/commit/06f4375202a66b3d0061f6ce0f9460393617b36e)), so this line can cause conflicts.

fix(build): remove old usage of korkVersion

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/PluginCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/AbstractHasPluginCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/AddPluginCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/DeletePluginCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/EditPluginCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/ListPluginsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/PluginEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/test/groovy/com/netflix/spinnaker/halyard/cli/command/v1/CommandTreeSpec.groovy
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Plugins.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/plugins/Manifest.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/plugins/Plugin.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PluginService.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/plugins/ManifestSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/PluginServiceSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/PluginProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/OrcaService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PluginsController.java

This PR is related to https://github.com/spinnaker/spinnaker/issues/4181.
This PR adds commands to Halyard to configure plugins, as well as lay down `plugins.yml` and configuration updates to `orca.yml` on deploy.
These files are used by Kork in order to enable plugins (https://github.com/spinnaker/kork/pull/325).

feat(plugins): adding halyard commands for plugins

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/PluginCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/plugins/PluginDownloadingEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Plugins.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/PluginService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/PluginProfileFactory.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/PluginsController.java

This PR is related to spinnaker/spinnaker#4181 and enables Spinnaker administrators to use halyard to enable downloading of plugin jars, as seen in https://github.com/spinnaker/kork/pull/358. 
Different environments used to run Spinnaker have varying constraints, in order to ensure plugins can be used in all environments, we added the ability to download plugins via Kork at runtime. By default, downloading of plugin jars will be disabled, but if the Spinnaker administrator trusts the download location, they can enable plugin jar downloading. Spinnaker users (application owners) will not have the ability to add plugins.

feat(plugins): enable/disable downloading plugins

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

add the ability to turn on the artifacts rewrite  through halyard

feat(artifacts): add feature flag to turn on artifactsRewrite

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditProviderCommand.java

Small edit to output when running `hal config provider kubernetes edit --help`...
`Due to how the Kubenretes provider`
s/Kubenretes/Kubernetes

fix(docs): s/Kubenretes/Kubernetes

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/telemetry/AbstractEnableDisableTelemetryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/telemetry/TelemetryCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/telemetry/TelemetryEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/telemetry/TelemetryEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/test/groovy/com/netflix/spinnaker/halyard/cli/command/v1/CommandTreeSpec.groovy
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Telemetry.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/TelemetryService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/LdapValidator.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/validate/v1/security/LdapValidatorSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/EchoProfileFactory.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/TelemetryController.java

Adds new configuration fields for telemetry. 
```
telemetry
enabled (enabled by default)
endpoint
instanceId
```
[spinnaker/spinnaker#4738](https://github.com/spinnaker/spinnaker/issues/4738)

feat(telemetry): adds endpoint and enable settings for stats collection

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Saml.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/SamlValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/config/v1/secrets/DecryptingObjectMapper.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SamlConfig.java

Corresponding kork PR: https://github.com/spinnaker/kork/pull/372
There have been some requests to support the SAML metadata.xml file as a secret. This does so on the Halyard side and moves the SAML "file:" prefix logic to the object mapper. `metadataRemote` and `metadataLocal` in the halfconfig both get assigned to `metadataUrl` in the service yamls, so we only add the "file:" prefix if `metadataUrl` is a file path.
@plumpy PTAL?

feat(secrets): Support SAML metadata as secret

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/saml/EditSamlCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Saml.java

Adds to https://github.com/spinnaker/gate/pull/907 by making the user attribute for email address configurable through halyard commands
Helps fix : https://github.com/spinnaker/spinnaker/issues/4924

fix(saml): make email address configurable

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/newrelic/CanaryNewRelicCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/newrelic/account/NewRelicAddCanaryAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/newrelic/account/NewRelicCanaryAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/newrelic/account/NewRelicEditCanaryAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/AbstractCanaryServiceIntegration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/Canary.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/newrelic/NewRelicCanaryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/newrelic/NewRelicCanaryServiceIntegration.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KayentaProfileFactory.java

This allows New Relic to be added as a kayenta canary service via halyard.
The only bit of this I wasn't sure about is how this new field will get generated in to the hal config. I'm guessing that a halyard version update will do something similar to `hal config generate` to get it in there?

feat(canary): add newrelic as canary service

---

build.gradle

Only test code is written in groovy, so we never have to worry about java code depending on groovy code; remove the override that is causing java source files to be compiled with the groovy compiler.

chore(core): Compile using the java compiler

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java

Fix for https://github.com/spinnaker/spinnaker/issues/4906
The method was returning the path of the `kubeconfig` file instead of its contents, when the file was stored locally.

fix(kubeconfig): Get contents of local kubeconfig files

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Plugins.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/plugins/Plugin.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/plugins/ManifestSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/plugins/PluginSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/PluginServiceSpec.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/PluginProfileFactory.java

Spinnaker operators should be able to override default plugin config values. This PR enables Spinnaker operators to configure plugin overrides via the hal config file. 
A hal config could contain the following in order to override the options for a particular plugin:
```
plugins:
plugins:
- name: test
enabled: true
manifestLocation: https://github.com/armory/stage-plugin/blob/master/manifest.yml
options:
example:
url: blah
port: 2000
nested:
list:
- last
- first
```
I am also correcting the copy+paste error for Manifest.java's copyright.

feat(plugins): enable plugin config overrides

---

install/macos/InstallHalyard.sh

My java version:
```bash
java --version 
$ openjdk
$ OpenJDK Runtime Environment (build 13+33)
$OpenJDK 64-Bit Server VM (build 13+33, mixed mode, sharing)
```
My Halyard version:
```bash
hal -v
$ 1.24.0-20191002142815
```

fix(halyard/installer): Add support for Java version 13

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ResourceConfig.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/HalconfigParserMocker.groovy
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/GenerateService.java

Halyard uses `halyard.halconfig.directory` for both `halconfigDirectory` and `halconfigPath`. With this PR:
- Halyard only uses `HalconfigDirectoryStructure` to build the correct path.
- We can override the directory used. The goal is to be able to temporarily point Halyard to a separate directory to read the user's configuration.
Note after that `localBomPath` still uses the same property but it's in `halyard-core` so without an easy way to refactor.

feat(config): HalconfigDirStruct source of truth, allow override

---

Dockerfile.ubuntu

The slim/alpine image uses 1000/1000 as the uid and gid for the `spinnaker` user. Doing the same for the Ubuntu image makes it simpler for installers like the Helm chart to use either image variant.

fix(build): `spinnaker` user/group id=1000 in Ubuntu image

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/HaEchoValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/SamlValidator.java

The SAML validator currently is getting the file contents of the metadata file instead of the file path, which causes the validator to fail. This PR fixes that bug.

fix(saml): get saml file path instead of file contents in saml validator

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitrepo/GitRepoAddArtifactAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/artifacts/gitrepo/GitRepoEditArtifactAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/artifacts/gitrepo/GitRepoArtifactAccount.java

Adding a new git repo account from a hal command will fail if you don't explicitly specify the `--ssh-trust-known-hosts` parameter, because the field is a boolean primitive type in the `GitRepoArtifactAccount` class. With the change to `Boolean`, this bug is fixed.

fix(artifacts/gitrepo): use Boolean class instead of primitive

---

Dockerfile.local

The container we had been using hasn't been updated in months. See
spinnaker/spinnaker#5204.

chore(release): Use the alpine containers instead of openjdk

---

Dockerfile.local

You can't specify a username in a k8s securityContext, only a uid. So
the uid 1000 is special and we need to keep the `spinnaker` user with
that ID.

fix(container): set the spinnaker user to uid 1000

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

`-XX:UseCGroupMemoryLimitForHeap` was deprecated in Java 8u191. It's functionality is now enabled by default. `-XX:MaxRAMFraction` was also replaced by the (more flexible) `-XX:MaxRAMPercentage`.
https://www.oracle.com/technetwork/java/javase/8u191-relnotes-5032181.html
Java 8 will still launch with the old flags, but ≥10 will not, so we need this for the move to Java 11.
We've been using Java ≥8u191 in every service since Spinnaker 1.14.0. So this version of Halyard will still successfully deploy 1.14.0, but not 1.13.0 or earlier. (Because we we're hardcoding the version of the JDK in Echo to 8u111 until then, probably accidentally.)
Probably this setting belongs in the `Dockerfile`for each service, not in Halyard, but that's a battle for another day.

fix(java11): remove deprecated JVM flags

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/FileService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java

Closes https://github.com/spinnaker/spinnaker/issues/5305
When kubeconfig is stored remotely, Halyard shouldn't try to modify it in place because clouddriver will download it from remote source anyway.

fix(kubernetes): Only load kubeconfig if it's a local file

---

build.gradle
halyard-config/halyard-config.gradle
halyard-deploy/halyard-deploy.gradle

Also updating dependencies: `clouddriver`, `front50` and `fiat` so they are use the same latest Spring Boot version (2.2.4)

feat(build): Enable local Maven repo when detecting SNAPSHOT dependency

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/deploy/ApplyDeployCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/BakeDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/Deployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/DistributedDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/KubectlDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/LocalDeployer.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/DeploymentController.java

This PR introduces `--wait-for-completion-timeout-minutes` option for `hal deploy apply` command and allows us to overwrite its 10 minutes default timeout value. The issue is reported in https://github.com/spinnaker/spinnaker/issues/5185.

feat(deployment): Overwrite deploy command's timeout value

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/AbstractAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/AbstractDeleteAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/AbstractHasAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/AbstractListAccountsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/DeleteAccountCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/ListAccountsCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/gcb/GoogleCloudBuildEditAccountCommand.java

GoogleCloudBuildAccountCommand directly implements AbstractHasAccountCommand. This is ok currently since Google Cloud Build is the only CI service that uses account instead of master. However, it blocks adding new account-based CI service to halyard since a lot of logics need to be duplicated across packages. This commit is aimming to abstract some common parts for account-based commands which makes adding a new CI service much easier.

refactor(ci): Make AbstractAccountCommand reusable

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/CiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/account/AbstractGetAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildGetAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/CiType.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/codebuild/AwsCodeBuild.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/codebuild/AwsCodeBuildAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/AwsCodeBuildService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/AwsCodeBuildController.java

Igor configuration for AWS CodeBuild is already merged https://github.com/spinnaker/igor/commit/8422a0a08275e1ef15cbb9863b10b245339fbd4a
This PR allows users to configure AWS CodeBuild accounts through halyard command line tool.
Test steps:
1. `cd` into halyard root directory
2. Run `./gradlew` to start halyard daemon
3. Run `./halyard-cli/build/install/halyard-cli/bin/halyard-cli config ci codebuild account add <ACCOUNT> --account-id <ACCOUNT_ID> --assume-role <ROLE> --region <REGION>` to test adding account
4. Run `./halyard-cli/build/install/halyard-cli/bin/halyard-cli config ci codebuild account get <ACCOUNT>` to test getting account
5. Run `./halyard-cli/build/install/halyard-cli/bin/halyard-cli config ci codebuild account list` to test listing accounts
6. Run …

feat(codebuild): Add support for manipulating AWS CodeBuild accounts

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2ServiceTest.groovy

Adding a flag to switch readiness to TCP probe. The reason for that is to enable deployments with mTLS where the `wget` readiness probe won't work. We could also allow users to provide their own `exec` command to use a valid client certificate but that's not covered by this PR :)
To enable the TCP probe, add the following to service-settings/<service>.yml:
```
kubernetes:
useTcpProbe: true
```

feat(kubernetes): Enable TCP probe for containers

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Telemetry.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/EchoProfileFactory.java

This is a follow-up to spinnaker/kork#503 and /spinnaker/echo#770 where we added deploy method and version. 
This change in halyard allows sending the telemetry information with the deployment method and version.

feat(telemetry): add ability to report deploy method

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2DeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2GateService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java

It looks like gate and deck were overriding `buildServiceSettings` just to avoid calling `setAddress`. But then when the JVM flags got added to that `buildServiceSettings`, they both missed that functionality. Since `deck` doesn't use a JVM, that's no big deal, but for `gate` it's an issue.
Held my nose and went for a minimally invasive change rather than a more holistic cleanup.
Fixes spinnaker/spinnaker#5483

fix(gate): apply the JVM flags to gate

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AbstractEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/account/AccountCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

Related to: https://github.com/spinnaker/governance/blob/master/rfc/eol_kubernetes_v1.md
- **refactor(kubernetes): separate v1 and v2 account validators**
The goal of this small refactor is to make it easier to reason about which validators in `KubernetesAccountValidator` apply to V1 vs. V2 accounts, so that we can easily remove the V1 validators after the release of 1.21. Previously, we applied some validators to both types of accounts and had in-validator checks against `providerVersion`. Instead, let's extract the V1-only validation logic into its own methods, also containing the logic to derive `DeploymentConfiguration` into a V1-only Docker Registry validator.
- **feat(kubernetes): add warning for v1 accounts**
Adds a warning linking to the Kubernetes V1 Provider EOL RFC so that …

feat(kubernetes): prepare for upcoming removal of V1 provider

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/AbstractEditCiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/ci/codebuild/AwsCodeBuildEditCiCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/ci/codebuild/AwsCodeBuild.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Cis.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ci/CiService.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/ci/CiController.java

1. Add an AbstractEditCiCommand class that could be inherited from. For now only codebuild account
command extends this class. There could be more in the future.
2. Mark assume-role and account-id as not required so that the static credentials could be used directly
3. Add an API in halyard daemon to set custom fields for CI providers
Example:
```
codebuild:
enabled: true
accessKeyId: 'access-key-id'
secretAccessKey: 'secret-access-key'
accounts:
- name: my-codebuild-account
accountId: '123456789012'
assumeRole: role/spinnakerManaged
region: us-west-2
- name: my-codebuild-eu-central-1
accountId: '123456789012'
assumeRole: role/spinnakerManaged
region: eu-central-1
- name: my-codebuild-no-assume-role
region: us-west-2
```
In the config above, `my-codebuild-account` will use static …

feat(codebuild): Add support for static credentials

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/ConfigCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/stats/AbstractEnableDisableStatsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/stats/StatsCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/stats/StatsEditCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/stats/StatsEnableDisableCommandBuilder.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/Daemon.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/services/v1/DaemonService.java
halyard-cli/src/test/groovy/com/netflix/spinnaker/halyard/cli/command/v1/CommandTreeSpec.groovy
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/NodeFilter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Stats.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Telemetry.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/DeploymentService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/StatsService.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/StatsValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/EchoProfileFactory.java
halyard-web/src/main/java/com/netflix/spinnaker/halyard/controllers/v1/StatsController.java

This is largely a `s/telemetry/stats/g` change, with some minor tweaks to ignore the old `telemetry` block (see `DeploymentConfiguration.java`). This change enables telemetry stats by default, and makes https://github.com/spinnaker/halyard/pull/1550 obsolete.
One known effect of this will be that all existing instance IDs will be regenerated. This may show a bump in unique instance counts as users upgrade their Halyard instances. Since there is only 118 28-day-active instances anyway, I think it'll largely be swallowed by the expected increase of newly enabled instances reporting metrics.
@ezimanyi Once this is in and Halyard is released, we'll need to indicate that the newly released Halyard version is required for 1.19.0.

feat(stats): Rename telemetry to stats, enable by default

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/DeploymentConfiguration.java

Slack is littered with people having this issue. It looks like this field was added in halyard 1.23 on 8/27/2019. So anyone with a config after that will have this issue. Perhaps worth a 1.32.1 release?
FYI Cameron: because of the weird way Halyard works, it writes default values for everything into the Halyard config file. Which means basically every single person has a `plugins` stanza in their Halyard config and when you delete that `plugins` field, they'll get parsing errors. So it's basically not safe to ever completely remove a field from a Halyard `Node` class. :sob: 
Fixes spinnaker/spinnaker#5606

fix(config): Ignore any existing `plugins` stanzas.

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringProfileFactory.java

This change breaks deploying any version of Spinnaker <= 1.18
using Halyard, so is being reverted.
This reverts commit 4ed4d2635640d97fdd5746f1ac567d664238101e.

fix(plugins): Revert add plugins to all services (#1559)

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/Front50ProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KayentaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/OrcaProfileFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringProfileFactory.java
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringProfileFactorySpec.groovy

Now that PF4J has been introduced to Spinnaker, Halyard should deploy plugin configuration to the individual services.
Previous discussion on slack: https://spinnakerteam.slack.com/archives/CK9FK4XDF/p1582934543022800
Previous PR: https://github.com/spinnaker/halyard/pull/1559
I tested this with the `spinnaker-release-1.19.x-latest-unvalidated` service builds and setting the spinnaker version to `1.18.0` to ensure plugin configs weren't sent to the services.

feat(plugins): add plugins to all services

---

Dockerfile.local

removed by https://github.com/spinnaker/halyard/commit/43dfc6744ea6dbe6fd65cb349a53696d96329dae
In addition to putting back something that was there previously, openssl is in the ubuntu
container, so let's have it here as well.
Not sure whether `fix` is really fair here?  Maybe this is more `feat` ?

fix(container): restore openssl to alpine image

---

startup/debian/hal

Currently if the Halyard daemon was created by another user, we kill it and try to start one of our own (likely failing as we probably don't have permission to kill it).
This is because we look up the PID in the pid file, then try to see if the process exists with 'ps' but don't pass the '-e' flag to get all processes (including those created by other users). This is particularly important given that the Halyard install process specifically asks you to specify a user with which to run Halyard.

fix(daemon): Don't try to kill daemon created by another user

---

build.gradle

Whoops, missed this part that used to be in init-publish.gradle.
This is how it's done in all the other microservices now.

chore(build): enable the spinnaker project plugin

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile
Dockerfile.slim
Dockerfile.ubuntu
halyard-proto/halyard-proto.gradle

Also:
* use a Java 11 JRE
* fix compilation for developers who aren't likely to have the cross-compilation plugin enabled

chore(java11): Compile with Java 11 (but targeting Java 8)

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

In preparation for strongly typing the rest of the Halconfig for Kleat, let's remove as many unneeded feature flags as possible. Since the `appengineContainerImageUrlDeployments` has not been used by Deck since release 1.11, let's remove the command to set it and simply ignore the field in existing Halconfigs.

feat(cli): remove unused appengine feature flag

---

Dockerfile.slim
Dockerfile.ubuntu

(a patch to `release-1.34.x`)
Fixes spinnaker/spinnaker#5685

chore(jre): revert to the Java 8 JRE

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

We [replaced](https://github.com/spinnaker/deck/pull/8175) Deck's stage-specific feature flags with a single `hiddenStages` setting , so we should remove their corresponding Halyard commands.
* feat(cli): remove Travis feature flag 
* feat(cli): remove Wercker feature flag 
* feat(cli): remove Gremlin feature flag 
* feat(cli): remove infrastructureStages feature flag
Corresponding docs PR: https://github.com/spinnaker/spinnaker.github.io/pull/1807

feat(cli): remove Travis, Wercker, Gremlin, and InfrastructureStages feature flags

---

Dockerfile.slim
Dockerfile.ubuntu

Lately we've been seeing the following Docker `RUN` command failing when building a Halyard container:
```
Step 12/18 : RUN curl -f -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_RELEASE}/bin/linux/amd64/kubectl &&     chmod +x ./kubectl &&     mv ./kubectl /usr/local/bin/kubectl
---> Running in cba63cce119f
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
curl: (56) OpenSSL SSL_read: Connection reset by peer
The command '/bin/sh -c curl -f -LO https://storage.googleapis.com/kubernetes-release/release/v${KUBECTL_RELEASE}/bin/linux/amd64/kubectl &&     chmod +x ./kubectl &&     mv ./kubectl /usr/local/bin/kubectl' returned a non-zero code: 56
```
[Sample …

fix(containers): Add retry to Docker containers downloading kubectl

---

halyard-backup/halyard-backup.gradle
halyard-cli/halyard-cli.gradle
halyard-config/halyard-config.gradle
halyard-deploy/halyard-deploy.gradle
halyard-proto/halyard-proto.gradle
halyard-web/halyard-web.gradle

removes explicit version opinion which was causing the build to blow up
in some dependency resolution cases (:halyard-web:depInsight
--configuration runtimeClasspath --dependency kork-core)
also was causing the transitives of kubernetes-client not to end up in
the application/deb

fix(build): use bom for kubernetes-client version

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/dockerRegistry/DockerRegistryCommandProperties.java

As reported in https://github.com/spinnaker/spinnaker/issues/5538, the `sortTagsByDate` flag has prohibitive performance implications for registries with tens or hundreds of thousands of tags. However, we learned from conversations in Slack and at the Kubernetes SIG that users with smaller registries still find this flag valuable. Let's at least add a warning to the documentation, and in the future we can revisit either removing the flag or improving the performance of its implementation if the Docker V2 API ever supports fetching tags chronologically (or even batching requests for individual tags to get their creation date).
Corresponding Kleat PR: https://github.com/spinnaker/kleat/pull/28

feat(docs): document poor performance of sortTagsByDate flag

---

gradle.properties
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/canary/google/GoogleCanaryAccountValidator.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/persistentStorage/GCSValidator.java

The changes to the retry logic updated some fields from Long to int (because we won't be waiting 24 days between retries); this commit just updates the places we called them in Halyard to pass an int.

fix(google): Update constructors to account for retry changes

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Partially reverts: https://github.com/spinnaker/halyard/pull/1620
Given the confusion on Slack and GitHub, let's replace the `artifacts` and `artifacts-rewrite` commands until no supported Spinnaker release consumes these flags.  Users on 1.20 will still get the `tooHighMessage` letting them know that these parameters are no longer necessary.

fix(cli): replace artifacts commands

---

startup/debian/hal

Fixes spinnaker/spinnaker#5705
I'm not sure what I was thinking with this original PR; adding the -e flag will return all processes regardless of PID, and is not necessary when passing a PID.
This is causing halyard to fail to startup because we think that the daemon is always running.
This reverts commit 4a686e906fbfce8ef565c3c1aeadffa74ad6535e.

fix(daemon): Fix startup failure by reverting incorrect ps usage

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/EditFeaturesCommand.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Partially reverts https://github.com/spinnaker/halyard/pull/1619
We need to support Gremlin in Halyard until we release Spinnaker 1.22, because 1.19 Orca still reads this flag.

fix(cli): replace gremlin commands for 1.18 and 1.19 compatibility

---

halyard-deploy/src/main/resources/git/install.sh

I suppose I could put in something to check for Java 11, but only looking at the version of java in your $PATH seems like a pretty naïve way to go about doing this check, since there are myriad ways you could have a JDK configured for Gradle.

fix(local-git): remove the Java version check from Halyard local-git deployment

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/ArtifactSourcesConfig.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/WriteableProfileRegistryProperties.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2RedisService.java
halyard-web/config/halyard.yml
install/Installer.sh
release/promote.sh

This also modifies the promotion script to move the built container image from `nightly` to `releases` repo.

feat(boms): Change default dockerRegistry to GAR

---

halyard-deploy/halyard-deploy.gradle
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/BakeService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/bake/debian/BakeDebianServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v1/KubernetesV1DistributedService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/LocalService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianDeckService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianServiceProvider.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/git/LocalGitService.java

Since the removal of the Kubernetes V1 provider, Clouddriver no longer has a dependency on the `fabric8` library. Given problematic `fabric8` upgrades in the past, let's try to remove Spinnaker's dependency on this library. Halyard currently uses `fabric8`'s `Strings.join` method in several places; let's replace these with Java's built-in `String.join` when possible (i.e, when the arguments to be joined extend `CharSequence`), and `String.format` otherwise.
The upcoming deprecation of distributed deployments using the V1 provider will remove Halyard's dependency on `fabric8:kubernetes-client`.

refactor(deps): remove fabric8-utils dependency

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/FeaturesServiceSpec.groovy

Removes the following unused properties from `Features`:
- `auth`: We write `features.auth` to Deck's profile by checking `deploymentConfiguration.getSecurity().getAuthn().isEnabled()`, not this field, which isn't written to by calling a CLI command anyway.
- `fiat`: We write `features.fiat` to Deck's profile by checking `deploymentConfiguration.getSecurity().getAuthz().isEnabled()`, not this field, which is also not written to by calling a CLI command.
- `entityTags`: Halyard does not support enabling of entity tags; not sure how this field ended up here but it is not used.

refactor(config): remove unused feature properties

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckDockerProfileFactory.java

When building Deck as a container, several environment variables are required when using SSL. However, the AUTH_ENABLED and FIAT_ENABLED environment variables are only read from Deck's settings.js when doing local development. When building Deck as a container, auth and fiat configs are read from the features configuration block, not environment variables, so we can safely remove this code.

refactor(deck): remove unneeded env vars from DeckDockerProfileFactory

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

I lied, _this_ is the final cleanup of unread bindings made in Deck's profile factory.

refactor(deck): remove unneeded notifications.enabled binding

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/tasks/v1/DaemonTask.java

This will make the logs more readable as we move from this:
`RUNNINGCollected child task [Deploy spin-redis]`
to this:
`RUNNING Collected child task [Deploy spin-redis]`

style(core): Add missing space to log

---

.mergify.yml

Was trying to figure out why mergify cancelling a check on @mattsanta's [first Halyard PR](https://github.com/spinnaker/halyard/pull/1706) (:tada:) caused the PR build to fail and noticed this duplicate line in the mergify config, which is likely not the actual problem here, but thought I'd remove it if we can while I was here.

fix(mergify): remove duplicate line from mergify.yml

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/KubernetesV2ClouddriverProfileFactory.java

Parsed kubeconfig returned by the object mapper is null when the kubeconfig file is empty so I added a null check. Fixes the following reported issue: spinnaker/spinnaker#5224
Furthermore, extracted some of the work from processKubernetesAccount into separate methods in hopes of making the method more readable.

fix(halyard): Replaced NPE caused by empty kubeconfig file when running 'hal deploy apply' with a more descriptive exception.

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

Since [this change](https://github.com/spinnaker/buildtool/pull/48) to spinnaker/buildtool, the OSS release changelog gists have been published with one top-level gist per minor release and individual files for each patch release. However, Halyard and Deck continued to expect one changelog per patch release named "changelog.md."
Although we have[ replaced the What's New modal changelog experience with a link to the changelog on spinnaker.io for users moving forward,](https://github.com/spinnaker/deck/pull/8341) let's write the correct changelog to settings.js for Halyard users deploying to a pre-1.21 version of Spinnaker.

fix(profile): write correct changelog file name to Deck settings.js

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/deployment/v1/ServiceProviderFactory.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/services/v1/DeployService.java

Related to: https://github.com/spinnaker/spinnaker/issues/5749
* Since ProviderVersion was only ever relevant to KubernetesAccount, move the enum from Provider to KubernetesAccount before deprecating it. Hopefully this will prevent any future cloud providers from needlessly including the providerVersion field in every account.
* We have included warnings that V1 accounts cannot be used for a Distributed install for a couple of Halyard releases; let's remove these for the next release.

refactor(kubernetes): deprecate ProviderVersion

---

CONTRIBUTING.md
docs/adding-a-config-parameter.md
docs/deprecating-fields.md

Related to: https://github.com/spinnaker/spinnaker/issues/5757, https://github.com/spinnaker/spinnaker/issues/5749
Given that Halyard investment is waning, let's document `ValidForSpinnakerVersion` as the path to field deprecation, rather than adding a policy of only supporting fields that exist in a supported Spinnaker version (as described in the above GitHub issues).
* feat(docs): improve discoverability of contributor docs 
* feat(docs): add field deprecation docs 
* feat(docs): document how to add minimum Spinnaker version to new fields

feat(docs): add deprecation documentation

---

docs/commands.md
gradle.properties
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/security/authn/saml/EditSamlCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/security/Saml.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/security/SamlValidator.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SamlConfig.java

Halyard changes for https://github.com/spinnaker/gate/pull/1269

feat(authn/saml): New optional SAML parameter for signing messages

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Account.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/azure/AzureAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dcos/DCOSAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/dockerRegistry/DockerRegistryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/ecs/EcsAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/CommonGoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/huaweicloud/HuaweiCloudAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/oracle/OracleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/tencentcloud/TencentCloudAccount.java

Instead of ignoring `providerVersion` in the base Account class, ignore it in each non-Kubernetes subclass, so that `providerVersion: v1` is respected for legacy Kubernetes accounts.

fix(cli): ignore providerVersion in all non-Kubernetes account types

---

install/macos/InstallHalyard.sh

Support Java 14 in the installation script for macOS.

fix(install): support Java 14 in installation for macOS

---

install/debian/InstallHalyard.sh

We should be able to run with any version of Java >=8. Java 7 has been EOL for over five years now, so if they still have that installed as their primary JDK, we probably have other issues. Let's just skip the version check entirely.
There are many valid ways someone could install Java. I think it's a fair assumption that someone installing Halyard should know how to install Java. So let's remove the part where we try to install an unnecessarily old version for them.
@maggieneterval (as build cop): there's some chance that the end-to-end tests are depending on `InstallHalyard.sh` to install Java. I don't really know how to figure that out, so I'll just try to fix it ASAP if it all blows up.
Fixes GoogleCloudPlatform/spinnaker-for-gcp#196.

fix(install script): Don't be so particular about Java versions

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/KubernetesSettings.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/service.yml

This allows adding customized annotations to Kubernetes service.
There are many cases that we want to add annotations to Kubernetes Service.
One example is Google Cloud Platform's [Network endpoint group (NEG)](https://cloud.google.com/load-balancing/docs/negs). This required to add a NEG configuration in Kubernetes Service annotation.
But currently, halyard doesn't allow to add it. It allows only `podLabels`, `podAnnotations`, `serviceLabels`. (ref: [podAnnotations, podLabels and serviceLabels, Spinnaker](https://spinnaker.io/reference/halyard/custom/#podannotations-podlabels-and-servicelabels))
Therefore, I've added to use this in many cases.
After this PR has merged, I will like to update the spinnaker.github.io document as well.

feat(kubernetes): allow adding custom service annotations

---

gradle.properties
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/google/GoogleDistributedService.java

This includes updates to google-java-format and ktlint, so requires some
formatting changes. These were made with a simple `./gradlew spotlessApply`.

chore(spotless): upgrade spinnaker gradle plugin

---

halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/LocalDiskProfileReader.java
halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/registry/v1/Versions.java
halyard-core/src/test/groovy/com/netflix/spinnaker/halyard/core/registry/v1/VersionsSpec.groovy
halyard-core/src/test/groovy/com/netflix/spinnaker/halyard/core/resource/v1/LocalDiskProfileReaderSpec.groovy
halyard-deploy/src/test/groovy/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/SpringProfileFactorySpec.groovy

Addresses bug with local BOM deployments where the 'local:' is not pruned from the version string before converting to a SemVer object. See https://github.com/spinnaker/spinnaker/issues/5703 for details.
Also addresses bug with orderBySemVer where versions which were supposed to be treated as equivalent were not actually being treated as such if they weren't the exact same string. For example, according to the spec, 1.0.0-00000 is supposed to be equal to 1.0.0-99999 since lessThan is not supposed to care about the part after the hyphen. However, 1.0.0-00000 was treated as lessThan 1.0.0-99999 because of the secondary naturalOrder sorting.
Also addresses bug with LocalDiskProfileReader where it does not add the ".tar.gz" file extension to profileName when readArchiveProfile like …

fix(local-bom): Fix issues blocking use of locally hosted configuration files

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/datadog/CanaryDatadogCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/canary/datadog/EditCanaryDatadogCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/datadog/DatadogCanaryServiceIntegration.java

- allows halyard command edit canary datadog
- allows setting metadataCachingIntervalMS in the same manner as prometheus

fix: add edit canary datadog

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/kubernetes/KubernetesAccountValidator.java

I am using 0 cacheThreads on one of my accounts to disable caching as it uses a lot of resources and fills redis up.
On previous halyard versions it did not complain, but now, setting it to 0 (zero) complains about it.
Deploying with `--no-validation` works fine, but it is not elegant.
If there is no other way to disable caching for some account, could you allow to use 0 (zero) ? It can still default to 1, but the use of 0 helped us a lot.

refactor(kubernetes): Allow cacheThreads 0. This will disable cache for an account.

---

halyard-deploy/src/main/resources/kubernetes/manifests/service.yml

Hi
Service annotations are in the metadata object.
When i tried to `deploy apply` i got this :
```
error: error validating "STDIN": error validating data:
ValidationError(Service): unknown field "annotations" in
io.k8s.api.core.v1.Service; if you choose to ignore these errors, turn
validation off with --validate=false
```

fix(kubernetes): fix custom service annotations

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Features.java

Related to: https://github.com/spinnaker/spinnaker/issues/5939
This flag gates legacy, pre-Kayenta stages in Deck's canary module that are likely not used by OSS users. To reduce confusion, deprecate this flag.

feat(config): add upperBound/tooHighMessage for mineCanary feature flag

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/plugins/Plugin.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/model/v1/ExtensibilitySpec.groovy

For plugins that do not use extensions, it would be nice to support top-level configuration.
closes https://github.com/armory-plugins/armory-observability-plugin/issues/21

feat(plugins): support top level plugin config

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

The `liveManifestCalls` flag was [removed](https://github.com/spinnaker/clouddriver/pull/4904) from Clouddriver; update Halyard to indicate that it is no longer necessary when upgrading to 1.23.

feat(cli): add upperBound for liveManifestCalls flag

---

release/promote.sh

Reverts #1724 (which itself was a rollback of #1653 and #1663) to turn this back on.

feat(releases): Publish Halyard containers to Artifact Registry

---

.github/workflows/build.yml
.github/workflows/pr.yml
.github/workflows/release.yml
Dockerfile.compile

Halyard compiles to Java 11 as of #1802.

chore(java11): Remove Java 8 from the CI systems.

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2RedisService.java

The `kubernetes-spinnaker` project seemingly exists solely to host this one image. I have no idea why. Let's move it into its own Artifact Registry repository in the CDF-owned `spinnaker-community` project.
Also, the version of Redis in this image is 3.2.11, which is three years old, but I suppose that's a problem for another day.

chore(redis): Move Halyard's redis image into the CDF-owned GCP project

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/aws/AwsEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/aws/AwsAccount.java

Enabling the use of the externalId parameter when assuming a role prevents the "confused deputy" problem.
https://docs.aws.amazon.com/IAM/latest/UserGuide/id_roles_create_for-user_externalid.html#external-id-purpose
Depends on: https://github.com/spinnaker/clouddriver/pull/4968

feat(aws): Adding property externalId to AWS account config for assuming roles.

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

Adjusted CloudFoundry validations due to changes on CF code used to query spaces introduced by https://github.com/spinnaker/clouddriver/pull/5071
Now the validator doesn't depend on clouddriver internal objects, and instead depends on retrofit API interfaces, still exposed by clouddriver.

feat(validations/cf): Updated CF client for validations

---

docs/commands.md
gradle.properties
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundryEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudfoundry/CloudFoundrySpaceFilterMapConverter.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudfoundry/CloudFoundryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java

https://github.com/spinnaker/clouddriver/pull/5088
https://github.com/spinnaker/clouddriver/pull/5103
This ticket is to support the new field added to a CF account.

feat(cf): bump CD version add Space Filter to Halyard for CF 

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/canary/google/GoogleCanaryAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/GcsPersistentStore.java

When the Front50 version was updated #1848 a change for GcsStorageService was introduced.
Prior to the rewrite of GcsStorageService, front50 accepted either null or empty string as the bucket location; now that GcsStorageService is in kotlin and does not use a String? for the field, an error occurs on trying to create the GcsStorageService.
PRs related spinnaker/front50#934

fix(gcs): Fix validation error when bucketLocation is not specified

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/kubernetes/KubernetesEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccount.java

The kubernetes account configuration was missing the cache-interval-seconds option, this change adds the capability to configure kubernetes account with cache-interval configuration in the cloud driver.

feat(kubernetes): Add CacheIntervalSeconds config to Kubernetes

---

gradle.properties
halyard-cli/halyard-cli.gradle
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/providers/cloudfoundry/CloudFoundryAccountValidator.java
halyard-core/halyard-core.gradle
halyard-deploy/halyard-deploy.gradle
halyard-web/halyard-web.gradle

This effectively combines the autobump PRs for [clouddriver](https://github.com/spinnaker/halyard/pull/1892), [fiat](https://github.com/spinnaker/halyard/pull/1868), [front50](https://github.com/spinnaker/halyard/pull/1893), and [spinnaker-gradle-project](https://github.com/spinnaker/halyard/pull/1885), along with the maven coordinate change from `com.netflix.spinnaker` to `io.spinnaker`.
There are also some other version changes to use dependencies that exist on maven central, though I haven't been able to exercise them much because...
There have been [some changes to clouddriver-cloudfoundry](https://github.com/spinnaker/clouddriver/pull/5294) that mean we need some tweaks here too.  Or at least I get the following compiler errors:
```
$ ./gradlew build
> Task …
```

fix(build): use versions of dependencies that are available on maven central

---

halyard-backup/halyard-backup.gradle
halyard-config/halyard-config.gradle
halyard-core/halyard-core.gradle
halyard-deploy/halyard-deploy.gradle

fix(vulnerability): Remove fixed version of commons-io dependency to accommodate safer version from kork.

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/ConfigSource.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/distributed/kubernetes/v2/KubernetesV2Service.java
halyard-deploy/src/main/resources/kubernetes/manifests/persistentVolumeClaimVolume.yml

I needed to mount a persistentVolumeClaim in Rosco in order to build an AMI.
Some people may need this too.

feat(provider/kubernetes): Add persistentVolumeClaim support

---

halyard-proto/halyard-proto.gradle

Getting below conflict between spring plugin and protobuf plugin while upgrading spring boot 2.2.x(existing kork) to 2.3.x:
```"> Task :halyard-proto:generateProto FAILED> Task :halyard-core:compileJava
Note: /halyard/halyard-core/src/main/java/com/netflix/spinnaker/halyard/core/resource/v1/JarResourceReader.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.FAILURE: Build failed with an exception.* What went wrong:
Execution failed for task ':halyard-proto:generateProto'.
> protoc: stdout: . stderr: google/longrunning/operations.proto:33:8: Option ""php_namespace"" unknown.
deployments.proto: Import ""google/longrunning/operations.proto"" …
```

fix(halyard-proto): Removed specified version for com.google.protobuf:protobuf-java

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/validate/v1/StatsValidator.java

Noticed this message while running Halyard, which points to 404 page:
```
INFO Stats are currently ENABLED. Usage statistics are being
collected. Thank you! These stats inform improvements to the product, and that
helps the community. To disable, run `hal config stats disable`. To learn more
about what and how stats data is used, please see
https://www.spinnaker.io/community/stats.
```
Looks like the site is accessible under new address?

Fix link to stats

---

install/macos/InstallHalyard.sh

Added Java17 support for Halyard Installation on MacOS

fix(install): Support Java17 for Halyard Installation on MacOS

---

halyard-config/halyard-config.gradle

While upgrading spring cloud to Hoxton.SR12, we encountered below errors :
```
> Task :halyard-config:compileJava
/halyard/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/OraclePersistentStore.java:17: error: package javax.validation.constraints does not exist
import javax.validation.constraints.NotNull;
^
/halyard/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/OraclePersistentStore.java:18: error: package javax.validation.constraints does not exist
import javax.validation.constraints.Size;
^
/halyard/halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/persistentStorage/OraclePersistentStore.java:29: error: cannot find symbol
@NotNull
^
symbol:   class NotNull
location: class …
```

fix(dependency): Issue of missing javax.validation:validation-api dependency while upgrading the spring cloud to Hoxton.SR12 in kork

---

halyard-web/lib/systemd/system/halyard.service
halyard-web/pkg_scripts/postInstall.sh

1. Fixed bugs in systemd service.
2. Create spinnaker user in postinst script if it does not exist.
3. Set default user in postinst script to spinnaker instead of ubuntu.

Fix bugs in systemd service preventing halyard daemon from starting

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/CommonGoogleCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/google/GoogleEditAccountCommand.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/CommonGoogleAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/google/GoogleAccount.java

This is to address the issue [ #6660](https://github.com/spinnaker/spinnaker/issues/6660)
Two new fields(serviceAccountId & serviceAccountProject) need to be added to google account fields in hal config which will be used in clouddriver for service account impersonation. 
Updated hal commands documentation as well.

fix(provider/google): Added support to service account impersonation

---

halyard-proto/halyard-proto.gradle

Allow successfull build on M1 mac
This change is similar to: https://github.com/spinnaker/clouddriver/pull/5765
Relevant discussion: https://github.com/spinnaker/clouddriver/pull/5752#issuecomment-1214587680

chore(dependencies): update protobuf/protoc for m1 support

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/local/debian/LocalDebianRedisService.java
halyard-deploy/src/main/resources/debian/init.sh
halyard-deploy/src/main/resources/debian/install.sh
halyard-deploy/src/main/resources/debian/pre-bake.sh
halyard-deploy/src/main/resources/services/redis/install.sh
install/Installer.sh
install/debian/InstallHalyard.sh

1. Fixed various issues with the Debian installation scripts.
2. Removed Java installation from the script that halyard runs when applying a deployment, because Java would already need to be installed to install Halyard and start the daemon.
3. Changed the minimum Ubuntu requirement from 14.04 to 18.04 since anything prior to 18.04 is out of support.
4. Removed option for specifying a user and home directory, since the Halyard package depends on the user being `spinnaker` and creates the `spinnaker` user if it does not exist.

fix(install): Fixed various bugs in the Debian installation scripts

---

halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/NestableCommand.java
halyard-cli/src/test/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommandTest.java

Some of the boolean flags that are parameterized via jcommander are not working
See new unit test added that are failing with the current jcommander version
Parameters that are saved as private boolean like `--help` work, but not the
ones attached to more complex method_x(booalean y). There is not much documentation
in jcommander for those so I suspect a bug, since attaching them to methods with
a signature using Boolean instead of boolean do work.
This fixes issue reported https://github.com/spinnaker/spinnaker/issues/6700
in addition to `--quiet` it also fixes `--debug`, `--alpha` and `--color`

fix(halyard): cli boolean flags not working

---

halyard-deploy/src/main/resources/debian/install.sh
halyard-web/config/halyard.yml
halyard-web/lib/systemd/system/halyard.service

1. Spinnaker and Halyard services are not enabled once they are installed, and do not start automatically on reboot.
2. The Halyard service is added as a dependency to a non-existent unit user.target in the systemd unit file.
3. The Debian artifact repository URL still points to Bintray.

fix(install): Enable Halyard and Spinnaker services to start on reboot, and fixed Debian artifacts URL

---

halyard-deploy/src/main/resources/debian/install.sh

Resolves the following issue:
```bash
root@e306cf20f7c5:/# hal deploy apply
+ Get current deployment
Success
+ Prep deployment
Success
Validation in default.stats:
- INFO Stats are currently ENABLED. Usage statistics are being
collected. Thank you! These stats inform improvements to the product, and that
helps the community. To disable, run `hal config stats disable`. To learn more
about what and how stats data is used, please see
https://spinnaker.io/docs/community/stay-informed/stats.
+ Preparation complete... deploying Spinnaker
+ Get current deployment
Success
+ Apply deployment
Success
+ Run `hal deploy connect` to connect to Spinnaker.
Updating apt package lists...
Adding Spinnaker apt repository
/home/spinnaker/.hal/default/install.sh: line 73: sudo: command not found
gpg: …
```

fix(install): Fix issue running Halyard within a docker container that does not have sudo installed

---

halyard-web/halyard-web.gradle

The property spring.config.additional-location is redundant in halyard-web.gradle file. This property is set by class com.netflix.spinnaker.kork.boot.DefaultPropertiesBuilder in com.netflix.spinnaker.halyard.Main. So removing it from gradle file.

refactor(web): Clean up redundant spring property in gradle file

---

halyard-web/halyard-web.gradle
halyard-web/src/main/java/com/netflix/spinnaker/halyard/Main.java

Now that https://github.com/spinnaker/kork/pull/990 and https://github.com/spinnaker/kork/pull/1002 are in (and halyard consumes them), we don't need these changes here anymore.
Revert "fix(web): adjust configuration so that the halyard daemon starts with spring boot 2.4 (#1987)"
This reverts commit 442810565b8dd1f6529b6df6c8eace29117ea64c.

chore(web): clean up spring boot 2.4-related changes

---

Dockerfile.ubuntu

Apply docker best practice for debian/ubuntu bases docker images.
Also see the [official documentation](https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#run)

fix(docker image): cleanup /var/lib/apt/lists/* as it is a best practice

---

halyard-cli/halyard-cli.gradle

Another PR ideal to bump all the other libs that are WAY out of date... snakeyaml to 1.28 maybe? :P BUT fixes CVE scans.

fix(commons-text): Bump commons text for CVE

---

build.gradle

Spring boot 2.4.x removed JUnit5 vintage engine from [spring-boot-starter-test](https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.4-Release-Notes#junit-5s-vintage-engine-removed-from-spring-boot-starter-test). It is required for executing junit4 based test cases in halyard. So, introducing junit-vintage-engine dependency in build.gradle, using testRuntimeOnly() as suggested in section 3.1 of https://junit.org/junit5/docs/5.6.2/user-guide/index.pdf
After applying this fix, coverage increased from 54 to 227 test case executions.

fix(tests): Introduce junit5 vintage engine for running junit4 test cases over junit5 in halyard

---

halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultServerService.java

While upgrading the google-java-format version in [spinnaker-gradle-project](https://github.com/spinnaker/spinnaker-gradle-project/pull/195) to 1.11.0 and consuming it for halyard, encountered below error:
```
> Task :halyard-deploy:spotlessJava FAILED
Step 'google-java-format' found problem in 'halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/service/VaultServerService.java':
null
java.lang.reflect.InvocationTargetException
at jdk.internal.reflect.GeneratedMethodAccessor1806.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at com.diffplug.spotless.java.GoogleJavaFormatStep$State.lambda$createFormat$1(GoogleJavaFormatS …
```

refactor(variable): rename boolean variable "sealed" to avoid collision with in-built isSealed() method in Java 17.

---

halyard-cli/halyard-cli.gradle
halyard-cli/src/test/java/com/netflix/spinnaker/halyard/cli/command/v1/HalCommandTest.java
halyard-config/halyard-config.gradle
halyard-config/src/test/java/com/netflix/spinnaker/halyard/config/model/v1/providers/kubernetes/KubernetesAccountTest.java
halyard-core/halyard-core.gradle
halyard-deploy/halyard-deploy.gradle

Before refactor, total test cases executed were 173. 
After refactor, total test cases executed are 227.

refactor(tests): convert junit4 based testcases to junit5, clean up and unpin spock in halyard

---

halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/RetrofitConfig.java

to get a okhttp3.logging.HttpLoggingInterceptor$Level bean to fix the
```
***************************
APPLICATION FAILED TO START
***************************
Description:
Parameter 2 of constructor in com.netflix.spinnaker.config.OkHttp3ClientConfiguration required a bean of type 'okhttp3.logging.HttpLoggingInterceptor$Level' that could not be found.
Action:
Consider defining a bean of type 'okhttp3.logging.HttpLoggingInterceptor$Level' in your configuration.
```
message on startup.  More specifically, from
```
$ ./gradlew build halyard-web:installDist
$ docker build -f Dockerfile.slim -t halyard:test-me .
$ docker run --rm halyard:test-me
```

fix(config): import RetrofitConfiguration class

---

gradle.properties

This reverts commit 1ee701ba5a18000c7ac843638d14858ccfe6b5aa.
https://github.com/spinnaker/halyard/pull/2082 was generated from a tag on the release-1.32.x branch of front50.
Halyard is supposed to use versions of front50 from master, so revert this.
See https://github.com/spinnaker/spinnaker/projects/20#card-85655999 for a fix for this.

Revert "chore(dependencies): Autobump front50Version (#2082)"

---

halyard-core/src/test/groovy/com/netflix/spinnaker/halyard/core/registry/v1/VersionsSpec.groovy

It seems that typo is ignored while compilation by spockframework 1.3-groovy-2.5/groovy 2.5.15, however during upgrade of spockframework 2.0-groovy-3.0 and groovy 3.x, hit the test compilation error:
```
> Task :halyard-core:compileTestGroovy
startup failed:
/halyard/halyard-core/src/test/groovy/com/netflix/spinnaker/halyard/core/registry/v1/VersionsSpec.groovy: 119: unable to resolve class dev
@ line 119, column 13.
dev versions = ["1.0.0", badVersion]
^
1 error
> Task :halyard-core:compileTestGroovy FAILED
```

refactor(core/test): refactor typo in test based on spockframework

---

halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigDirectoryStructure.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParser.java
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/config/v1/HalconfigParserSpec.groovy
halyard-config/src/test/groovy/com/netflix/spinnaker/halyard/config/services/v1/HalconfigParserMocker.groovy
halyard-config/src/test/java/com/netflix/spinnaker/halyard/config/config/v1/HalconfigConfigurationTest.java

since tests like this fail in java 17 otherwise:
```
> Task :halyard-config:test
AccountServiceSpec > load an existent account node FAILED
java.lang.NullPointerException
at java.base/java.util.Objects.requireNonNull(Objects.java:209)
at java.base/sun.nio.fs.UnixFileSystem.getPath(UnixFileSystem.java:263)
at java.base/java.nio.file.Path.of(Path.java:147)
at java.base/java.nio.file.Paths.get(Paths.java:69)
at com.netflix.spinnaker.halyard.config.config.v1.HalconfigDirectoryStructure.getHalconfigPath(HalconfigDirectoryStructure.java:50)
at com.netflix.spinnaker.halyard.config.config.v1.HalconfigParser.transformHalconfig(HalconfigParser.java:159)
at com.netflix.spinnaker.halyard.config.services.v1.HalconfigParserMocker.mockHalconfigParser(HalconfigParserMocker.groovy:38)
at …
```

fix(config/test): provide a non-null halconfigDirectory in HalconfigParserMocker

---

docs/commands.md
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/ProviderCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudrun/CloudrunAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudrun/CloudrunAddAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudrun/CloudrunCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudrun/CloudrunCommandProperties.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudrun/CloudrunEditAccountCommand.java
halyard-cli/src/main/java/com/netflix/spinnaker/halyard/cli/command/v1/config/providers/cloudrun/CloudrunEditCommand.java
halyard-config/halyard-config.gradle
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Provider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/node/Providers.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudrun/CloudrunAccount.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/model/v1/providers/cloudrun/CloudrunProvider.java
halyard-config/src/main/java/com/netflix/spinnaker/halyard/config/services/v1/ProviderService.java
halyard-deploy/src/main/java/com/netflix/spinnaker/halyard/deploy/spinnaker/v1/profile/deck/DeckProfileFactory.java

This is part of https://github.com/spinnaker/governance/issues/302
Added all cloudrun commands in halyard.
halyard cloudrun commands:
1. hal config provider appengine [parameters] [subcommands]
account: Manage and view Spinnaker configuration for the cloudrun provider’s account
disable: Set the cloudrun provider as disabled
edit: Edit cloudrun’s app engine configuration.
enable: Set the cloudrun provider as enabled
2. hal config provider cloudrun account ACCOUNT [parameters] [subcommands]
add: Add an account to the cloudrun provider.
delete: Delete a specific cloudrun account by name.
edit: Edit an account in the cloudrun provider.
get: Get the specified account details for the cloudrun provider.
list: List the account names for the cloudrun provider.
3. hal config provider cloudrun …

feat(provider/google): Added all cloudrun commands in halyard
